### ISSUE TITLE
Prefix Config Using Incorrect Symbols

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#1]
The string for the mod name prefix colour is generating `ยง` instead of `§` for the values in the config.
It is generating `S:waila.cfg.nameprefix=ยง9ยงo` when it should be `S:waila.cfg.nameprefix=§9§o`.

Using the correct symbol when modifying the config works - loading the instance up with the string set to `§e` prints the mod name with yellow formatting - but it replaces the string with `ยงe` during load.

**Comment by TehNut** [comment]
The configuration is supposed to generate as `\u00a7` instead of the actual section symbol. I will properly escape the unicode.

**Comment by TehNut** [comment]
Not fixed yet :p

**Comment by ChloeDawn** [comment]
`*tongue face reaction*`
