### ISSUE TITLE
Entity Health Display Issues

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#10]
**There is a lack of spacing between the entity health and mod name string.
Entity health rendering also ignores `Alpha` transparency values. (See https://github.com/TehNut/HWYLA/issues/9)**

![2016-10-29_14 08 14](https://cloud.githubusercontent.com/assets/9869940/19829721/3144ba54-9de1-11e6-8276-6616c63c0a96.png)

**Comment by TehNut** [comment]
This was fixed in a4d057dfb82523ff3d9d0b7c908c0bdc28279e88

**Comment by ChloeDawn** [comment]
This issue was occurring after that change for me. I'll test again in a while just to be 100% sure.
