### ISSUE TITLE
Null pointer error when looking at Cheese Block from Animania

### ISSUE THREAD

**Issue by capnkirok** [TehNut-Mods/HWYLA#100]
See thread here on Animania git:
https://github.com/capnkirok/animania/issues/460

I personally don't see it in my testing, but OP does and provided crash log and details.

**Comment by TehNut** [comment]
This is the bit that's crashing.

https://github.com/TehNut/HWYLA/blob/961f8347796fedf2594e81f6fad12be91ddc1fb6/src/main/java/mcp/mobius/waila/overlay/RayTracing.java#L112-L122

The only way that can happen is if a plugin is returning `null` in `getWailaStack`. Which is invalid in 1.12, obviously.

**Comment by TehNut** [comment]
![image](https://user-images.githubusercontent.com/5789439/33243883-9f4dc79c-d2a2-11e7-8453-c376c2ec30a3.png)

Welp.

**Comment by capnkirok** [comment]
Yup. Updated from 1.11 and didn't check these.
