### ISSUE TITLE
server console (java.lang.NullPointerException) (1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [TehNut-Mods/HWYLA#102]
#### Issue Description:
hud spaming console for quite a long time

#### What happens:
when a player joins it seems to get spammmed on server side

#### What you expected to happen:
for it to acr normal and not cause java.lang.NullPointerException's to happen

#### Steps to reproduce:

1. have hwyla on server and cleint join a server with forge:1.12.2-2562
2. look around at things
3. profit
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.23-B38_1.12
- Minecraft: 1.12.2
- Forge: 1.12.2-2562

#### Possible Conflicting Mods (Provide their version, as well)
latest log server:
http://puu.sh/yIlI3/9a78b8a632.txt

**Comment by TehNut** [comment]
This would be caused by whatever mod adds the block that causes it not properly providing their `IFluidHandler`.
