### ISSUE TITLE
[1.12.2] Crash with Natura

### ISSUE THREAD

**Issue by LiskoSlayer63** [TehNut-Mods/HWYLA#105]
Every time when I place a maple wood block (added by Natura) the whole client crashes with `java.lang.NullPointerException`. I'm telling this to you because the crash is caused by Hwyla, not Natura. 

I uploaded the crash-log [here](https://pastebin.com/ketENyLC).

**Hwyla version:** 1.8.23
**Forge version:** 14.23.1.2561
**Minecraft version:** 1.12.2

**Comment by TehNut** [comment]
This crash is caused by some other mod returning a null stack in `IWailaDataProvider#getWailaStack`. Probably Natura.

**Comment by TehNut** [comment]
I have submitted a PR to Natura that will solve this. https://github.com/progwml6/Natura/pull/422
