### ISSUE TITLE
Suggestion: Vampirism Blood Count

### ISSUE THREAD

**Issue by princessbinas** [TehNut-Mods/HWYLA#106]
Until WALIA is updated for 1.12.2, I have been using this mod. It is very good and has some pros over the original WALIA (i.e. showing you what is in the furnace for both inputs and out put). The only problem I am encountering right now is the fact that HWYLA is unable to read the blood count on entities such as pigs, cows, chickens, villagers, etc. Is it possible for you to add this feature?

**Comment by TehNut** [comment]
This would be an issue on their end. Chances are, they are using `Waila` for the modid instead of `waila`. As of 1.11.2, all modids must be lowercase. Please report this to Vampirism.

**Comment by TehNut** [comment]
Actually now that I look, they moved Waila compat to a separate mod called [VampirismIntegrations](https://github.com/TeamLapen/VampirismIntegrations).
