### ISSUE TITLE
HWYLA crashes the whole game upon looking on a block with missing bottom part

### ISSUE THREAD

**Issue by Octelly** [TehNut-Mods/HWYLA#110]
#### Issue Description:
https://bitbucket.org/ProfMobius/waila/issues/242/issue-if-double-high-flower-missing-part
The problem is described there, but basically; it crashes when tall grass etc. doesn't have a bottom part. In this case it was the pineapple plant from Tropicraft.
#### What happens:
It crashes the whole game upon looking on tall grass etc. that doesn't have a bottom part
#### What you expected to happen:
HWYLA should have just showed what the block is.
#### Steps to reproduce:
1. Mod Minecraft with Tropicraft and HWYLA (I'm using WAWLA too, but as far as I'm aware, that shouldn't really change anything)
2. Generate a new world
3. Find a pineapple plant and look at it
4. Force shutting down internal server...
____
#### Affected Versions (Do *not* use "latest"):
- Hwyla: 1.8.20
- Minecraft: 1.12.2
- Forge: 8.0.99.99
#### Possible Conflicting Mods (Provide their version, as well)
Tropicraft - 7.1.0.26
WAWLA (What Are We Looking At - addon for WAILA) - 2.5.249

If any more info is needed, then just ask.

**Comment by TehNut** [comment]
Can you provide the specific crash report?

**Comment by TehNut** [comment]
The version you are using is from August and is 3 builds out of date. Try on the most recent version.

**Comment by ChloeDawn** [comment]
This crash is unrelated to the issue you referenced and is a bug on Tropicraft's end.
