### ISSUE TITLE
[1.12.2] Crash when Finishing Tier 3 Launch Pad [ExtraPlanets Compatibility]

### ISSUE THREAD

**Issue by CDAGaming** [TehNut-Mods/HWYLA#112]
#### What happens:
When making a Tier 3 Launch Pad from Extra Planets, a crash occurs at times when you finish building it

#### What you expected to happen:
Tier 3 Launch Pad successfully built

#### Steps to reproduce:
Unknown, irregular pattern of occuring.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.23-B38
- Minecraft: 1.12.2
- Forge: 14.23.2.2613

#### Possible Conflicting Mods (Provide their version, as well)
Extra Planets (1.12.2-0.2.1)

#### Crash Log
https://hastebin.com/iqejijazos.sql
https://hastebin.com/fetavubayu.vbs (Server-Side, after I crash)

**Comment by TehNut** [comment]
They are returning null in `getPickBlock` which is invalid.
