### ISSUE TITLE
Bold strings spill out of the box

### ISSUE THREAD

**Issue by josephcsible** [TehNut-Mods/HWYLA#113]
![2018-02-09_23 02 13](https://user-images.githubusercontent.com/16061266/36058410-55577238-0ded-11e8-9d9c-9fb56d2f93b4.png)

#### Issue Description:
Bold strings only expand the box the amount they would if they weren't bold, resulting in it overflowing outside of it.

#### What happens:
The string overflows the box.

#### What you expected to happen:
The box should resize to hold the string.

#### Steps to reproduce:

1. Look at a block that has a bold string
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Development version 71d87f5
- Minecraft: 1.12.2
- Forge: 14.21.1.2387

#### Possible Conflicting Mods (Provide their version, as well)

None

**Comment by josephcsible** [comment]
Looks like the fix for this got included in 1.8.24.

**Comment by TehNut** [comment]
Oops I meant to close this
