### ISSUE TITLE
Hatchery nest percentage not displayed anymore

### ISSUE THREAD

**Issue by Snottco** [TehNut-Mods/HWYLA#118]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
The 'percentage' of an egg in a hatchery nest is no longer shown

#### What you expected to happen:
The interface to display the 

#### Steps to reproduce:

1. Put egg in hatchery nest
2. Look at nest containing egg
3. N/A
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.24-B39_1.12
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2637

#### Possible Conflicting Mods (Provide their version, as well)
Hatchery 1.12.2 2.0

**Comment by ChloeDawn** [comment]
This has nothing to do with HWYLA itself, please report it to the Hatchery developers
