### ISSUE TITLE
Bucket Rendering Being Affected By Alpha Value

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#12]
**The rendering of the Forge bucket model is a bit broken when adjusting the `Alpha` value.**

![2016-10-30_10 50 42](https://cloud.githubusercontent.com/assets/9869940/19836098/d494bd00-9e8e-11e6-837c-397cd0332154.png)
![2016-10-30_10 50 17](https://cloud.githubusercontent.com/assets/9869940/19836097/d47e803a-9e8e-11e6-9909-f162e9f53a23.png)

**Comment by TehNut** [comment]
nope i broke lots of other things
