### ISSUE TITLE
[1.12.2] SMP Client Crash due to NPE

### ISSUE THREAD

**Issue by Morpheus1101** [TehNut-Mods/HWYLA#120]
Forge: v*.2678
Hwyla v: 1.8.25-B40

Crash report @ https://gist.github.com/Morpheus1101/fdbdb9bd2ec22f8abf6b4a6aa5b68665

**Comment by TehNut** [comment]
Malisis Doors is returning null [here](https://github.com/Ordinastie/MalisisDoors/blob/c2bba4f4d3da2b7b776cecf4be1f6a714a72679f/src/main/java/net/malisis/doors/block/Door.java#L301).
