### ISSUE TITLE
Plant info is not showing on Agricraft crop sticks.

### ISSUE THREAD

**Issue by Lusaphor** [TehNut-Mods/HWYLA#125]
Currently Hwyla is not showing the plant on Agricraft's crop sticks, all it shows is the crop stick itself. Waila used to do this and I do not know if another mod might be interfering but I havei tried removing several different mods and it still was a problem. Im using HWYLA  1.8.26-B41, Forge 2709, and Agricraft 2-12-0-1.12.0-a4.

**Comment by TehNut** [comment]
They need to implement it.
