### ISSUE TITLE
NullPointerException when placing Climatiser from Binnie's Genetics

### ISSUE THREAD

**Issue by mopsyd** [TehNut-Mods/HWYLA#126]
#### Issue Description:
See stack trace:
https://paste.dimdev.org/owinisosaj.mccrash

This error threw over 1,000 times within two seconds (placed and immediately broke suspect block). It is difficult to tell exactly how many instances of the error occurred, because the log stopped recording due to the volume of them almost immediately.

#### What happens:
Causes massive volume of NullPointerExceptions, which flood the log beyond the point of being able to capture additional messages. Also causes a huge amount of lag in game (with the Vanilla Fix mod), or immediate crash (without vanilla fix mod).

#### What you expected to happen:
Expected to be able to place blocks without causing game crashes due to Hwyla failing to render the info for them.

#### Steps to reproduce:

1. Place a Climatiser from Binnie's Genetics while Hwyla is installed.
2. See stacktrace for possible other mods causing conflict.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.26-B41_1.12.2.jar 
- Minecraft: 1.12.2
- Forge: 14.23.4.2750

#### Possible Conflicting Mods (Provide their version, as well)

See provided stacktrace.

**Comment by mopsyd** [comment]
I'm not sure if this is an upstream error with Binnie's Genetics, but it seems to occur from some tank/fluid handling aspect of Hwyla from the looks of the stack trace. Eg:

```
Caused by: java.lang.NullPointerException
    at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61)
```

**Comment by TehNut** [comment]
Binnie's is returning `true` in `hasCapability(...)` but `null` in `getCapability(...)`
