### ISSUE TITLE
Tooltip Config Preview Misaligned

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#13]
**Tooltip preview doesn't render as intended in the config screen.**

![2016-10-30_10 50 39](https://cloud.githubusercontent.com/assets/9869940/19836107/0f4e88ae-9e8f-11e6-9391-c9d9863c8834.png)

**Comment by TehNut** [comment]
I think the background's X coordinate is being bounded by the edge of the screen. I probably missed adding that bounding to the foreground
