### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TheNimbleNinja** [TehNut-Mods/HWYLA#131]
#### Issue Description:
https://gist.github.com/TheNimbleNinja/cf22aded40d37fef01c05e1757f763a6

#### What happens:
 error keeps poping up

#### What you expected to happen:

no constant waila error

#### Steps to reproduce:

no idea

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.26-B41_1.12.2
- Minecraft:  1.12
- Forge:14.23.5.2772

**Comment by TehNut** [comment]
This is caused by whatever block you were looking at having mismatched logic in `hasCapability` and `getCapability`
