### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by TheNimbleNinja** [TehNut-Mods/HWYLA#132]
#### Issue Description:
when placing down any furnace from furnace overhaul a error happens that floods the screen
https://gist.github.com/TheNimbleNinja/10b12c8c153b1847487fc36ede403ac9

#### What happens:
error floods the screen

#### What you expected to happen:
nothing happen

#### Steps to reproduce:

1. place down furnace
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.26-B41_1.12.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2772

**Comment by TehNut** [comment]
They ignore facing in `hasCapability` and check facing in `getCapability`. The logic does not match. This is on their end.
