### ISSUE TITLE
Crash upon world entering world

### ISSUE THREAD

**Issue by deneth-weerasinghe** [TehNut-Mods/HWYLA#135]
#### Issue Description:
(using personal modpack)
Cannot enter a world without crash

#### What happens:
Game crashes during/after loading a save (not sure which)
Here's the crash report: https://pastebin.com/77NpzhaN

#### What you expected to happen:
Be able to load world and play

#### Steps to reproduce:

1. Launch game (using MultiMC)
2. Load any world
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.26-B41_1.12.2
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2796-universal

**Comment by TehNut** [comment]
Try without smartmoving.

**Comment by deneth-weerasinghe** [comment]
> Try without smartmoving.

Thanks, that worked. Guess I shouldn't have downloaded a mod in alpha 😅
