### ISSUE TITLE
[19w03a] Crash when loading saves

### ISSUE THREAD

**Issue by KannaHayabusa** [TehNut-Mods/HWYLA#138]
#### Issue Description:
Crash when loading saves, 19w03a Fabric

#### What happens:
After the much longer loading screen of 1.14 pre-release, the game saves and closes.

#### What you expected to happen:
The game properly loading the world and allowing one to play the game.

#### Steps to reproduce:

1. Have HWYLA and Fabric installed
2. Start the game
3. Load a pre-existing save or make a new one
4. ...
5. Profit!
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.9.2-44
- Minecraft: 19w03a
- Fabric: 0.3.2.96

**Comment by TehNut** [comment]
Yeah they rewrite the hit result system. I'll get to it when I have time

**Comment by KannaHayabusa** [comment]
Take your time, mate!

**Comment by TehNut** [comment]
d343844a4178813e1cc47ff5aa30db0bfb614cbd

**Comment by TehNut** [comment]
https://minecraft.curseforge.com/projects/hwyla/files/2662265
