### ISSUE TITLE
Berry bushes aren't detected.

### ISSUE THREAD

**Issue by MelanX** [TehNut-Mods/HWYLA#139]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
Berry bushes aren't detected.
![2019-01-20_09 36 54](https://user-images.githubusercontent.com/26039509/51436985-644e4000-1c97-11e9-8e50-e1afa19dd53c.png)

#### What you expected to happen:
- Berry bush will be detected

#### Steps to reproduce:

1. Look at berry bush

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.14-1.9.4-46
- Minecraft: 19w03c
- Fabric API: 0.1.4.77

**Comment by MelanX** [comment]
Crops on farmland will not be detected, too

**Comment by TehNut** [comment]
Awaiting approval on Curse, [here's a link](https://tehnut.info/maven/mcp/mobius/waila/Hwyla/1.14-1.9.5-47/Hwyla-1.14-1.9.5-47.jar) to the maven artifact.
