### ISSUE TITLE
Inventory Tooltip Ignoring NBT

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#14]
**Tooltip ignoring metadata of items and displaying icon for metadata `0` of that item.**

**Example of `forestry:sapling`.**

![2016-10-30_11 03 14](https://cloud.githubusercontent.com/assets/9869940/19836182/7bc43992-9e90-11e6-9359-3aa08ea0e7e7.png)

**And an example of some bees.**

![2016-10-30_11 02 28](https://cloud.githubusercontent.com/assets/9869940/19836178/639108aa-9e90-11e6-95d3-ac1e87db3d19.png)

**Comment by TehNut** [comment]
56c18868793d538e75afe9e7348415dcd2bc41cd
