### ISSUE TITLE
Lores

### ISSUE THREAD

**Issue by MelanX** [TehNut-Mods/HWYLA#141]
#### Issue Description:
Lores aren't detected.

#### What happens:
![2019-01-25_18 05 09](https://user-images.githubusercontent.com/26039509/51760907-ef7e6a00-20cb-11e9-9f72-4f6582bae55e.png)

#### What you expected to happen:
There is text.

#### Steps to reproduce:

1. Think of steps to reproduce Kappa
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.14-1.9.6-48
- Minecraft: 19w03c
- Fabric: 0.1.4.77

**Comment by TehNut** [comment]
https://minecraft.curseforge.com/projects/hwyla/files/2668680
