### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by MelanX** [TehNut-Mods/HWYLA#142]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Game crashes:
https://pastebin.com/8x7DU7ap

#### What you expected to happen:
Not crashing :D

#### Steps to reproduce:

1. Start 19w04b with HWYLA
2. go to server
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.14-1.9.7-49
- Minecraft: 19w04b
- Fabric: 0.1.4.77

**Comment by TehNut** [comment]
This is REI

**Comment by MelanX** [comment]
🤦‍♂️ sorry!
