### ISSUE TITLE
Suggestions - Adjustable distance at which HWYLA can pick up on information.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TehNut-Mods/HWYLA#147]
I love the mod but the distance I can read things at is - painfully short. The one probe has the right idea with rather distant targets still being picked up. Honestly being 10 blocks from any view target can be a pain especially if target is moving frequently.

Other than that I love the mod.

I am using 1.12.2 by the way.

**Comment by TehNut** [comment]
No. I do not agree with TOP on many things and that is one of them. It makes much more sense to only render the tooltip for things you can actually interact with at that time.
