### ISSUE TITLE
Filled Fluid Containers Appear Empty In Inventory Tooltip

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#15]
**Filled buckets, and any other modded fluid containers such as Forestry cans do not render their fluid layer.**

![2016-10-30_10 59 55](https://cloud.githubusercontent.com/assets/9869940/19836165/13e7ea44-9e90-11e6-8182-282727ca33b6.png)

**Comment by TehNut** [comment]
Same as #14

**Comment by ChloeDawn** [comment]
Isn't this a rendering related issue though? Not NBT related.

**Comment by TehNut** [comment]
Forge Buckets are differentiated by NBT
