### ISSUE TITLE
[1.13.2] Mod Fails to load on Client

### ISSUE THREAD

**Issue by Morpheus1101** [TehNut-Mods/HWYLA#151]
Forge: 25.0.71
Hwyla: 1.10.0-B52

` Caught exception during event FMLLoadCompleteEvent dispatch for modid waila java.lang.NoSuchMethodError: net.minecraftforge.forgespi.language.ModFileScanData.getAnnotations()Ljava/util/List; at mcp.mobius.waila.Waila.lambda$loadComplete$7(Waila.java:93) at mcp.mobius.waila.Waila$$Lambda$1614/89739120.accept(Unknown Source) at java.util.ArrayList.forEach(ArrayList.java:1249) at mcp.mobius.waila.Waila.loadComplete(Waila.java:92) at mcp.mobius.waila.Waila$$Lambda$1329/177448350.accept(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:201) at net.minecraftforge.eventbus.EventBus$$Lambda$1301/188729048.invoke(Unknown Source) at net.minecraftforge.eventbus.EventBus.post(EventBus.java:257) at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:105) at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$1290/1118442276.accept(Unknown Source) at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) at java.util.function.Consumer$$Lambda$1265/848187074.accept(Unknown Source) at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) at java.util.function.Consumer$$Lambda$1265/848187074.accept(Unknown Source) at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:100) at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120) at net.minecraftforge.fml.ModList$$Lambda$1321/171864308.accept(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by TehNut** [comment]
Thanks forge https://github.com/MinecraftForge/ForgeSPI/commit/99faed94701e008e13acef2f2f51be39227d73b5

**Comment by TehNut** [comment]
My favorite kind of bug fix is when I don't have to do a single fucking thing. https://github.com/TehNut/HWYLA/commit/45f94e5ba363252a192d4a464453615050260623
