### ISSUE TITLE
Crash issue with Armor Toughness Bar??? (Project Ozone 3)

### ISSUE THREAD

**Issue by Leo40Git** [TehNut-Mods/HWYLA#153]
#### Issue Description:
I have contacted the modpack devs and also done a bit of my own testing, this bug is caused by Armor Toughness Bar (a mod I added that's not included in PO3) and traces back to Hwyla.

#### What happens:
The game crashes after finishing the loading stages. Crash log: https://pastebin.com/CSEzfZfH

#### What you expected to happen:
The game to launch to the main menu without crashing?

#### Steps to reproduce:
1. Install the Project Ozone 3 modpack, version 3.0.38 (latest as of this issue)
2. Add the Armor Toughness Bar mod
3. Launch and wait for the game to finish loading

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.26-B41
- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- Armor Toughness Bar: 2.1

____
Issue on ATB's repo: https://github.com/Tfarcenim/Toughness-Bar/issues/4

**Comment by TehNut** [comment]
I am unable to reproduce this
