### ISSUE TITLE
Wont work at all, 

### ISSUE THREAD

**Issue by chosenplayer** [TehNut-Mods/HWYLA#157]
#### Issue Description:
I basically add it to my (1.12.2) mods folder and then i open my game, and then I check my mod settings and its not there.

#### What happens:
It's not in the mod settings and doesnt work

#### What you expected to happen:
For it to show up at all

#### Steps to reproduce:

1. Place in mods folder
2. Click play
3. Profit
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.10.2
- Minecraft: 1.12.2
- Forge: 8.0.99.99

#### Possible Conflicting Mods (Provide their version, as well)
Dynamic HUD may be a problem 3.5.4.0

![](https://srv2.imgonline.com.ua/result_img/imgonline-com-ua-twotoone-jlHdKttMhByK7ht0.png)

**Comment by UpcraftLP** [comment]
have you tried
- using a forge version that actually exists?
- using a HWYLA version for the version of minecraft that you are using?

**Comment by TehNut** [comment]
Hwyla 1.10.* is for Minecraft 1.13.
