### ISSUE TITLE
Rendering Bug With Cavern Mod.

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#16]
**Minecraft version:** 1.10.2

Looking at a block causes blocks in the dimension to render weirdly.
Same bug as https://github.com/kegare/Cavern/issues/13 but I thought I should report it here too in-case it's an issue with WAILA/HWYLA itself, and since the other issue hasn't been responded to.

Mod: **[curseforge.com/projects/cavern](https://minecraft.curseforge.com/projects/cavern)**

Screenshots:

![2016-11-04_21 03 18](https://cloud.githubusercontent.com/assets/9869940/20022419/606a1f5e-a2d2-11e6-9711-16df3b8c7531.png)
![2016-11-04_20 59 45](https://cloud.githubusercontent.com/assets/9869940/20022367/156a7bf2-a2d2-11e6-949a-711724b73ec8.png)

**Comment by TehNut** [comment]
Does anything print to console?

**Comment by ChloeDawn** [comment]
Log from startup, to loading into one of the dimensions, pausing the game, looking at a block, then pausing the game again. 

[fml-client-latest.log](https://gist.github.com/InsomniaKitten/ab2c3a6f7842955314329103210f3610)

Screenshots were taken with OptiFine active, but the bug still occurs without it. Log was recorded without OptiFine active.

I tried disabling the mining level overlay (bottom-right) in the config, but that didn't resolve it.

**Comment by TehNut** [comment]
I was hoping there would be some GL spam in there.

**Comment by MrNinja93** [comment]
Tried to replicate this just now in a pack (added Cavern to it) and I'm not experiencing it (using B11 and Cavern 1.3.4)

Edit: Screenshot is caveland dimension

Edit 2: For the sake of testing went down to B9 and not happening with that version either. 

![2016-11-06_02 16 56](https://cloud.githubusercontent.com/assets/21979276/20034885/24131d76-a3c7-11e6-9d29-6612c7092722.png)

**Comment by ChloeDawn** [comment]
Did you have OptiFine installed?
Please provide your `fml-client-latest.log` file, your `options.txt` file, and your `optionsof.txt` file (if present).

P.S. Great choice of resource pack.

**Comment by MrNinja93** [comment]
No optifine and my [options.txt](https://gist.github.com/MrNinja93/5adf4d3520c9da72bcbf8c3530d87848)

Edit: quick filename dump of my mods directory https://gist.github.com/MrNinja93/e4f527e92a7bcfb29a9d79aec477c9ba

[Fml-latest](https://gist.github.com/MrNinja93/b54c5d2c209874db8be2b1349f83b06d)

(and most mods have gone towards unity so might aswell unify the experience :P )

**Comment by TehNut** [comment]
@InsomniaKitten Are you able to reproduce this in a minimal environment?

**Comment by ChloeDawn** [comment]
I'll do some testing now. Check the issue I referenced in the original comment, their identical bug occurred in a minimal environment.

**Comment by TehNut** [comment]
Yeah but obviously there's some wonky stuff going on since it's not 100% reproduceable

**Comment by TehNut** [comment]
Could I get both of you to load your environments exactly as you've done before and hold `F3+C` until your game crashes so I can get a log? This may be caused by load order and GL states.

**Comment by MrNinja93** [comment]
[Debug crash log](https://gist.github.com/MrNinja93/fca8029219170fc45ccc732cb47f2ba2) 

Upped the forge version up to 2020 to be the same as InsomniaKitten's fml-client-latest above to see if it was forge and still nothing.

**Comment by MrNinja93** [comment]
Ok so did a minimal environment in a fresh profile just to check and it now happens. 

[Debug Crash](https://gist.github.com/MrNinja93/229fdf9381c83d8b2e9bba059ebbd23d)

Forge 2020
HWYLA B9
JEI 357
Cavern 1.3.4

Nothing else installed

Edit: JEI not needed to replicate, Another fresh instance without it and its still happening.

**Comment by TehNut** [comment]
Hrm. My wild guess is that Cavern is screwing with the GL state somewhere and not resetting it.

**Comment by MrNinja93** [comment]
Found the reason my initial pack wasn't having the issues Immersive Engineering stops it happening, soon as I remove that from the original pack it happens and as soon as I add it to the fresh profile with just cavern/HWYLA it stops. Whatever they do with the rendering system must fix it.

**Comment by TehNut** [comment]
I'm going to move HWYLA away from direct GL calls when I get home. I doubt it's the real source of this problem, but it may fix it.
