### ISSUE TITLE
Keybinds keep resetting

### ISSUE THREAD

**Issue by Madis0** [TehNut-Mods/HWYLA#160]
#### Issue Description:
The customized keybinds for HWYLA keep resetting to default after every Minecraft restart.

#### What happens:
Keybinds reset after customizing them.

#### What you expected to happen:
Keybinds persist across sessions.

#### Steps to reproduce:

1.  Install HWYLA to Fabric
2.  Open Minecraft
3.  Go to Options > Controls...
4.  Scroll to Waila and change the keybinds to something other than default
5.  Restart Minecraft
6.  Keybinds are the same as default (0, 1, 2)
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: v1.9.16
- Minecraft: 1.14
- Fabric:  Loader 0.4.2 build 132, API 0.2.7 build 127

#### Possible Conflicting Mods (Provide their version, as well)
N/A

**Comment by TehNut** [comment]
Does this happen with any other mod-added keybinds?

**Comment by Madis0** [comment]
Yes, seems like it is more related to Fabric in general.
