### ISSUE TITLE
Crash on server launch with 1.9.16-60

### ISSUE THREAD

**Issue by jonnyowenpowell** [TehNut-Mods/HWYLA#165]
#### What happens:
The server crashes, log attached below.
____
#### Affected Versions:

- Hwyla: 1.9.16-60
- Fabric API: 0.2.7+build.127
- Fabric Loader: 0.4.6+build.141 
- Minecraft: 1.14

[crash_error.log](https://github.com/TehNut/HWYLA/files/3145083/crash_error.log)

**Comment by TehNut** [comment]
https://github.com/FabricMC/fabric-loader/issues/112

@asiekierka pls ascii fix thank
