### ISSUE TITLE
Mod not recognized by Twitch

### ISSUE THREAD

**Issue by Wissi** [TehNut-Mods/HWYLA#169]
#### Issue Description:
When exporting a modpack for distribution Twitch says:
``This profile includes mod versions that are no longer available from Twitch. This pack may not be approved for public distribution.`` 
Even manually editing the ``manifest.json`` and ``modlist.json`` to include HWYLA it will not be downloaded by Twitch anymore. Is there an issue with the naming of the mod in Curse website or perhaps it's not set right in Curse for Twitch to recognize and download?

#### What happens:
Mod will not download using Twitch.

#### What you expected to happen:
Mod to be downloaded from within Twitch.

#### Steps to reproduce:
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla:  Hwyla-1.8.26-B41_1.12.2
- Minecraft:  1.12.2
- Forge:  14.23.5.2825

#### Possible Conflicting Mods (Provide their version, as well)

**Comment by TehNut** [comment]
I have changed nothing on my end. This is on Curse's side. I have no idea what could have gone wrong.
