### ISSUE TITLE
having a issue with crash barrier for Immersive Vechicle

### ISSUE THREAD

**Issue by zacharyhenry** [TehNut-Mods/HWYLA#172]
#### Issue Description:
i placed crash barriers from mod called Immersive Vechiels (MTS) and it doesnt show the popup box of what mod its from

#### What happens:
No popup box shows up

#### What you expected to happen:

? wheres the popup box?

#### Steps to reproduce:

1. place crash barrier item
2. hover my mouse over item
3. no popup box
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla:  v 1.8.26
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Possible Conflicting Mods (Provide their version, as well)
Immersive vechiels mod v14.3.0
![Minecraft_1 12 2_6_3_2019_1_26_17_PM](https://user-images.githubusercontent.com/49297302/58827994-fed96b00-8609-11e9-8c43-71b823d9ec05.png)
![Minecraft_1 12 2_6_3_2019_1_26_31_PM](https://user-images.githubusercontent.com/49297302/58827996-000a9800-860a-11e9-97ad-23aeb4b0dd4c.png)
![Minecraft_1 12 2_6_3_2019_1_52_58_PM](https://user-images.githubusercontent.com/49297302/58827998-013bc500-860a-11e9-8f25-c38b6783ffdf.png)
![Minecraft_1 12 2_6_3_2019_1_58_07_PM](https://user-images.githubusercontent.com/49297302/58827999-026cf200-860a-11e9-9166-dafe787224ba.png)
![Minecraft_1 12 2_6_3_2019_1_58_29_PM](https://user-images.githubusercontent.com/49297302/58828001-03058880-860a-11e9-8440-0dff9de6c622.png)

**Comment by TehNut** [comment]
This would be an issue on their end. Report it over there.

**Comment by zacharyhenry** [comment]
they told me it was something to do with " Go report that to waila mod author, not MTS, because that’s not caused by MTS. Waila maybe doesn’t work with obj model blocks ¯\_(ツ)_/¯"

**Comment by zacharyhenry** [comment]
all the other items in their mod works with ur mod accept this one item im new to modded minecraft ?

**Comment by zacharyhenry** [comment]
jerk

**Comment by zacharyhenry** [comment]
u could at least see why its not working with ur mod at least

**Comment by TehNut** [comment]
no :^)
