### ISSUE TITLE
issue with crash barrier

### ISSUE THREAD

**Issue by zacharyhenry** [TehNut-Mods/HWYLA#173]
u could at least look into it for me please they told me let u know ?

please i just want to know why this one modded item not working with ur mod

minecraft 1.12.2
forge 14.23.5.2838
waila 1.8.26

IV(MTS) 14.3.0

**Comment by zacharyhenry** [comment]
Go report that to waila mod author, not MTS, because that’s not caused by MTS. Waila maybe doesn’t work with obj model blocks ¯\_(ツ)_/¯

**Comment by TehNut** [comment]
This is an issue with their single specific block. All other mods work fine. Something about their block is acting as a special snowflake.
