### ISSUE TITLE
[1.14-forge] Using the API?

### ISSUE THREAD

**Issue by desht** [TehNut-Mods/HWYLA#175]
#### Issue Description:
Trying to import the Hwyla API for use in my mod (Modular Routers)

#### What happens:
My understanding is that the correct way to use the API is now to implement ``IWailaPlugin`` and annotate it with ``@WailaPlugin``.  While I can add a dependency on Hwyla, the ``@WailaPlugin`` annotation is not visible to my IDE, although all other classes/interfaces in ``mcp.mobius.waila.api`` are visible.  But I can see the WailaPlugin annotation in your Github repo (https://github.com/TehNut/HWYLA/blob/1.14_forge/src/main/java/mcp/mobius/waila/api/WailaPlugin.java), so it seems it's getting excluded somehow.

#### What you expected to happen:
To be able to use the ``@WailaPlugin`` annotation.

#### Steps to reproduce:

1. Tried a couple of ways to import the mod in my build.gradle:

```
compile "mcp.mobius.waila:Hwyla:${config.waila_version}:api" {
        transitive = false
}
```
```
compile "mcp.mobius.waila:Hwyla:${config.waila_version}" {
        transitive = false
}
```
```
compile fg.deobf  (project.dependencies.create("mcp.mobius.waila:Hwyla:${config.waila_version}") {
        transitive = false
 })
```
All with the same result.  So I'm not sure on the correct way to specify Hwyla as a dependency now.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla:  1.14.2-1.19.16-62
- Minecraft: 1.14.2
- Forge: 1-14.2-26.0.25

**Comment by TehNut** [comment]
The class appears to be in the jar so I'm not sure why it can't be seen
![image](https://user-images.githubusercontent.com/5789439/59553450-fc500d00-8f49-11e9-87a7-c068a71cfec1.png)

**Comment by TehNut** [comment]
Oh, you're pulling the Fabric version. The Forge version is `1.10.3-B61_1.14.2`.
