### ISSUE TITLE
[1.14.2 - Forge] Crash on World Entry

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/HWYLA#176]
#### Issue Description:
I am using HWYLA with no other mods. I am using the AT Launcher (Vanilla with Forge). The world loads and the game crashes immediately.
 
https://pastebin.com/uNHVwHvk
#### What happens:
When I load up a world (I also tried a new world) it loads it to 100% and the game crashes immediately. 

#### What you expected to happen:
World loads.

#### Steps to reproduce:
1. ?
2. ?
3. ?

____
#### Affected Versions:

- Hwyla: forge-1.10.3-B61_1.14.2
- Minecraft: 1.14.2
- Forge: 26.0.25

**Comment by ghost** [comment]
Same issue here. I am using the standard Minecraft Launcher with 1.14.2 Forge 26.0.33 and Hwyla Forge 1.10.3-B61_1.14.2. Minecraft on it's own loads fine, but as soon as you load a single player world this happens. Here is a link to my [crashlog](https://pastebin.com/yKAHEyYP).

**Comment by slasher333** [comment]
Ditto. I only have one other mod, and even without it I still have this problem.

**Comment by TehNut** [comment]
Caused by this change in Forge https://github.com/MinecraftForge/MinecraftForge/commit/da22fd40bfec6d93445d774bbce9bea9334db685

**Comment by TehNut** [comment]
https://minecraft.curseforge.com/projects/hwyla/files/2726609
