### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by RubiksCubei** [TehNut-Mods/HWYLA#180]
Minecraft：1.12.2

hope to add features：

1.Add pairs Hold Applied Energistics 2 Color Applicator Color support。
2.Adding support for liquid display in Mekanism pipeline。

English is not very good,sorry.

Thank you！

**Comment by ChloeDawn** [comment]
Hwyla is an API, it does not add mod support directly. These suggestions are something you should ask the developers of each mod to add to their own code.

**Comment by ChloeDawn** [comment]
Also, your English is good enough, do not worry ^^
