### ISSUE TITLE
Entity health sometime not displaying correctly

### ISSUE THREAD

**Issue by nathanrsxtn** [TehNut-Mods/HWYLA#181]
#### Issue Description:
Entity health display sometimes is wrong.
![2019-06-28_07 48 53](https://user-images.githubusercontent.com/37890449/60347263-26f28a80-997a-11e9-8ad1-1ce2ffbc1296.png)

#### What happens:
Attacking anything sometimes doesn't make the health display go the right amount while jumping.
#### What you expected to happen:
Attacking something makes the health go down the proper amount.
#### Steps to reproduce:

1. Find an entity
2. Attack it while jumping
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.26-841
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Possible Conflicting Mods (Provide their version, as well)
Tested with no other mods

**Comment by TehNut** [comment]
The display uses information directly from the server. Since health is a float, this could be a rounding error.

**Comment by nathanrsxtn** [comment]
The `Better PvP Mod` has a health display that is correct, so is there a way it can be fixed?

**Comment by TehNut** [comment]
I don't believe it is "correct". I have chosen to round down, they have chosen to round up. The correct value is somewhere in between.

**Comment by nathanrsxtn** [comment]
OK, that makes sense. Thanks for the help!
