### ISSUE TITLE
[1.12.2] Exceptions thrown in a block's getPickBlock() cause a client crash

### ISSUE THREAD

**Issue by praecipitator** [TehNut-Mods/HWYLA#185]
#### Issue Description:
HWYLA causes a crash when a preservation block from Erebus is placed. 
Here is the log: https://pastebin.com/qecEMq2k
Seems like exceptions caused by getPickBlock() called by HWYLA can take the entire client with them.

#### What happens:
When a preservation block from Erebus is placed, the client crashes. 

#### What you expected to happen:
When a preservation block from Erebus is placed, the client does not crash.
IMO the worst case should be HWYLA simply not showing anything if such an exception occurs, or "<invalid block>" or something like that.

#### Steps to reproduce:

1. Install Erebus and HWYLA.
2. Use the Staff of Preservation (and an Amber Star) to capture a mob. Notice how preservation blocks created this way do not cause any crashes.
3. Mine the created preservation block using a Silk Touch pickaxe.
4. Place the block back onto the ground.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.26-B41_1.12.2.jar
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal.jar

#### Possible Conflicting Mods (Provide their version, as well)
Erebus-1.0.30.jar

**Comment by TehNut** [comment]
This crash occurs within Erebus code and should be reported to them
