### ISSUE TITLE
Crash - 1.14.4 fabric loader

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/HWYLA#192]
Hi

I was playing your mod since first version.

Click on the link to see the latest report.
Other mods in the report are functionaly perfect.

https://paste.ee/p/9V4x5

I hope you fix this fast.

Thanks ...

**Comment by TehNut** [comment]
`waila requires {fabric-api-base @ [*]}`

Line 115 in your log. I hope you fix this fast.
