### ISSUE TITLE
[1.14-Forge] Items show incorrect modid in tooltips

### ISSUE THREAD

**Issue by Shadows-of-Fire** [TehNut-Mods/HWYLA#193]
The tooltip event no longer uses the correct creator modid as given by `Item#getCreatorModId`.  It appears to use the namespace of the item's registry name instead.

**Comment by TehNut** [comment]
Just needs a change here https://github.com/TehNut/HWYLA/blob/1c734c2f426b0bb64716fc5c3bb870e9053183dd/src/main/java/mcp/mobius/waila/utils/ModIdentification.java#L37

**Comment by Shadows-of-Fire** [comment]
`n u t`

**Comment by TehNut** [comment]
https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2777880
