### ISSUE TITLE
Crash on Forge 28.0.45

### ISSUE THREAD

**Issue by rollerce** [TehNut-Mods/HWYLA#194]
#### Issue Description:
Crashes on forge 28.0.45

#### What happens:
Server will not start.

#### What you expected to happen:
Server starting.

#### Steps to reproduce:

1. Attempt to start server.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-forge-1.10.4-B65_1.14.2.jar
- Minecraft: 1.14.4
- Forge: 28.0.45

**Comment by TehNut** [comment]
Update

**Comment by rollerce** [comment]
Disregard - download button gave me the wrong version.
