### ISSUE TITLE
NPE Console spam

### ISSUE THREAD

**Issue by MrNinja93** [TehNut-Mods/HWYLA#20]
This was present in base Waila and seems to have carried over to here, Some blocks/tile entities throw NPE's in server console when viewed, No crashes but if there's a load of players on the server I imagine that console log might get large.   

Using B11

Small sample log

```09.11 12:51:21 [Server] INFO [12:51:21] [Netty Server IO #3/WARN] [Waila]: Catched unhandled exception : [class net.bdew.gendustry.machines.apiary.TileApiary] java.lang.NullPointerException
09.11 12:51:21 [Server] INFO [12:51:21] [Netty Server IO #3/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:117
09.11 12:51:21 [Server] INFO [12:51:21] [Netty Server IO #3/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
09.11 12:49:29 [Server] INFO [12:49:29] [Netty Server IO #3/WARN] [Waila]: Catched unhandled exception : [class mcjty.rftools.blocks.endergen.EndergenicTileEntity] java.lang.NullPointerException
09.11 12:49:29 [Server] INFO [12:49:29] [Netty Server IO #3/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:117
09.11 12:49:29 [Server] INFO [12:49:29] [Netty Server IO #3/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
09.11 12:49:29 [Server] INFO [12:49:29] [Netty Server IO #3/WARN] [Waila]: Catched unhandled exception : [class crazypants.enderio.conduit.TileConduitBundle] java.lang.NullPointerException
09.11 12:49:29 [Server] INFO [12:49:29] [Netty Server IO #3/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:117
09.11 12:49:29 [Server] INFO [12:49:29] [Netty Server IO #3/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
09.11 12:49:28 [Server] INFO [12:49:28] [Netty Server IO #3/WARN] [Waila]: Catched unhandled exception : [class crazypants.enderio.machine.capbank.TileCapBank] java.lang.NullPointerException
09.11 12:49:28 [Server] INFO [12:49:28] [Netty Server IO #3/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:117
09.11 12:49:28 [Server] INFO [12:49:28] [Netty Server IO #3/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107```

**Comment by TehNut** [comment]
This seems to be an issue in ElecCore. I'll poke through and see what's up.

**Comment by MrNinja93** [comment]
If it is ElecCore I'm on an outdated version on the server so bare that in mind (updating everything in like 2/3 days)

**Comment by TehNut** [comment]
Could you try with at least an updated Eleccore so I can get the correct line numbers?

**Comment by TehNut** [comment]
Also does it ever print the same tile class more than once? The line starting with "Catched"

**Comment by MrNinja93** [comment]
Aha turns out elec core was the issue apologies, newest version doesn't seem to cause it (don't see why eleccore is calling NBT tags for everything in the first place but yeah...)

**Comment by TehNut** [comment]
Sweet, thanks for checking that.

> don't see why eleccore is calling NBT tags for everything in the first place

In order to get any Tile Entity data for use in the Waila tooltip, you need to write all the data to an NBT tag with [`IWailaDataProvider#getNBTData(...)`](https://github.com/TehNut/HWYLA/blob/1.10/src/main/java/mcp/mobius/waila/api/IWailaDataProvider.java#L83). That gets called on the server to collect the necessary data, then sent to the client for use.
