### ISSUE TITLE
It shows nothing for (Boats of all kind) and (Minecarts with Chest or Furnace)

### ISSUE THREAD

**Issue by sepsol** [TehNut-Mods/HWYLA#201]
Do you even check these issues on GitHub?!

**Comment by ChloeDawn** [comment]
Issues cannot be resolved if you do not specify the Minecraft version, mod loader version, and Hwyla version.

> Do you even check these issues on GitHub?!

If there is a ticket open for your problem already, don't open a duplicate ticket.

**Comment by sepsol** [comment]
I'm on Minecraft 1.14.4
Forge 28.1.61
HWYLA 1.10.6-B67

**Comment by TehNut** [comment]
https://github.com/TehNut/HWYLA/issues/199

**Comment by ChloeDawn** [comment]
Technically not a duplicate as the referenced ticket is from the Fabric version

**Comment by TehNut** [comment]
It is the same issue
