### ISSUE TITLE
[1.15pre] 🦀 statemanager is gone 🦀

### ISSUE THREAD

**Issue by Yoghurt4C** [TehNut-Mods/HWYLA#205]
it finally broke
https://hastebin.com/zifiqatugi.http

`Hwyla-fabric-1.14.2-1.9.17-66`
`Minecraft: 1.15 Pre-release 1`
`net.fabricmc:fabric-loader:0.7.1+build.173`
`fabric-api-0.4.13+build.263-1.15`

**Comment by TehNut** [comment]
Ok fine I'll mod again

**Comment by TehNut** [comment]
https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2831084
