### ISSUE TITLE
waila.cfg dont work

### ISSUE THREAD

**Issue by ChukiStrike** [TehNut-Mods/HWYLA#208]
### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
I edit this file, to put it to my liking, but the changes never arise effect in the game.
![iaObjHq](https://user-images.githubusercontent.com/38164175/70379687-eab35500-192f-11ea-869c-4c50a6be9cf9.jpg)
)

#### What you expected to happen:
I want it to have a transparent background and be pasted at the top left and disable keybind 1.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla:  Hwyla-1.8.26-B41_1.12.2
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2847-universal

#### Possible Conflicting Mods (Provide their version, as well)

![Sin título](https://user-images.githubusercontent.com/38164175/70379681-d7a08500-192f-11ea-8fbd-f4dd93b7d98d.jpg)

**Comment by TehNut** [comment]
Use the in-game editor

**Comment by ChukiStrike** [comment]
How can I use it in the game? I put /hwyla or /waila and nothing comes out.
Can you explain me please

**Comment by ChukiStrike** [comment]
@TehNut

**Comment by ChukiStrike** [comment]
But for the keybind=false?

**Comment by TehNut** [comment]
Use the controls menu like any other keybind..?
