### ISSUE TITLE
"hide_infestations" doesn't work

### ISSUE THREAD

**Issue by MythikAngel** [TehNut-Mods/HWYLA#209]
#### Issue Description:
When looking at  a Monster Egg (in a Stronghold for example), HWYLA shows it's an Infested Stone Brick, despite the option "hide_infestations" being enabled.

#### What happens:
HWYLA Shows "Infested Stone Bricks"
![2019-12-08_15 50 09](https://user-images.githubusercontent.com/35168042/70393615-067c3100-19ec-11ea-92a4-5231b2ccdbe7.png)

#### What you expected to happen:
HWYLA Shows "Stone Bricks"

#### Steps to reproduce:

1. Make sure "hide_infestations" is enabled in "waila_plugins.json" (it's enabled by default)
2. Look at an Infested Stone Bricks block

____
#### Affected Versions:

- Hwyla: Hwyla-fabric-1.15-pre4-1.9.19-70
- Minecraft: 1.15pre4
- Fabric: 0.7.2+build.174
- Fabric API: 0.4.19 build 272

#### Possible Conflicting Mods
No mods loaded other than Hwyla and Fabric API

**Comment by TehNut** [comment]
Technically the block was being hidden (which makes 0 difference in ~~most~~ ~~all~~ most cases) but the name wasn't.
