### ISSUE TITLE
EnderIO all conduits displaying Forge energy capability info 

### ISSUE THREAD

**Issue by MrNinja93** [TehNut-Mods/HWYLA#21]
Found this while testing the NPE problem finally got round to testing in SP with latest versions of both, Hwyla is showing forge energy info for all conduits (Item, fluid, redstone) 

Possibly to do with them registering conduits in world as [BlockConduitBundle](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java)

![2016-11-11_01 51 23](https://cloud.githubusercontent.com/assets/21979276/20201727/12d98420-a7b2-11e6-8743-7acced4f46ac.png)
![2016-11-11_01 51 26](https://cloud.githubusercontent.com/assets/21979276/20201728/12dcc996-a7b2-11e6-98db-4b38a607b147.png)

Hwyla : B12 (also happens with B11/B9 and I assume more)
EnderIO: 126
EnderCore: 58

**Comment by TehNut** [comment]
I only display the energy tooltip if the Block's TE returns true for `hasCapability(CapabilityEnergy.ENERGY, null)`. If EnderIO is returning true for all conduits, regardless of whether they store energy or not, this would be an EnderIO bug.

E: EnderIO is showing itself to have all sorts of issues with how they use capabilities...

**Comment by MrNinja93** [comment]
Fair enough suspected it was their end, Minor though so that's something.
