### ISSUE TITLE
Waila/Hwyla causes a crash

### ISSUE THREAD

**Issue by AnthonyGamingAG** [TehNut-Mods/HWYLA#211]
#### Issue Description:
I placed down an item called broken ring that is attached to a NPC on the ground and the game has forged to stop my world and return to title screen

#### What happens:
I got married to a NPC and she died  tried to use broken ring by putting it on the ground
Then the game crashed and forced me to title screen

#### What you expected to happen:
To function normally without crash and let me use staff of life and revive the NPC

#### Steps to reproduce:

1. Use spawn egg and spawn a NPC
2.  Get married by raising heart(right click the NPC-->gift-->diamond is the best way) and gift he/she a wedding ring 

3. use a creative broken ring item and right click on the NPC, then place it on the ground
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.26-B41_1.12.2
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2824

#### Possible Conflicting Mods (Provide their version, as well)
MCA-1.12.x-5.3.1-universal (Minecraft comes alive)
Just in case the crash log is needed because I dont know where to put it
https://paste.dimdev.org/ekemenahuf.mccrash

**Comment by TehNut** [comment]
> `java.lang.NullPointerException: mca:memorial from mod Minecraft Comes Alive returned a null ItemStack in getPickBlock(...). Please report this to them.`
