### ISSUE TITLE
Update to 1.15.1

### ISSUE THREAD

**Issue by ppoozl** [TehNut-Mods/HWYLA#214]
Hello. I want to use HWYLA on forge 1.15.1. So I modified your code to be able to run on 1.15.1. I'd like to contribute my code. You can merge my codes.

**Comment by ppoozl** [comment]
I can't create new branch on your repo and merge to other branch is inappropriate.

**Comment by ChloeDawn** [comment]
You can make a pull request to an existing branch and the target branch of the PR can be changed before it is merged.

**Comment by TehNut** [comment]
Thanks https://github.com/TehNut/HWYLA/pull/215
