### ISSUE TITLE
[1.14.4] Missing Hearts in Hwyla Overlay turn Pink. [Image Inside]

### ISSUE THREAD

**Issue by Gbergz** [TehNut-Mods/HWYLA#217]
#### Issue Description:
Note: I'm playing on a **Modpack** but this is happening on a Clean "Vanilla" Instance w/ only the mod installed too.

____
#### Steps to reproduce:

1. Look at a Living Entity's Health in the Hwyla Overlay.
2. Hurt the mob with a sword, bring down it's health.
3. Missing hearts turn pink.
4. Done.

**Edit:** Also noticed the existing hearts have a black background. No transparency.
____
#### Image: (Look in the top left)
[https://i.imgur.com/QnUuQbz.png](https://i.imgur.com/QnUuQbz.png)

____
#### Affected Versions:

- Hwyla: **1.10.7-B71_1.15.1**
- Minecraft: **1.15.1**
- Forge: **30.0.41**

**Comment by ppoozl** [comment]
Render system changed a lot in 1.15.1. I just renamed function names to make it work on forge 1.15.1. I can't fix it.

**Comment by Gbergz** [comment]
Ah.. gotcha!
