### ISSUE TITLE
Problem adding Hwyla integration to my mod

### ISSUE THREAD

**Issue by waylanderou** [TehNut-Mods/HWYLA#224]
#### Issue Description:

I'm an trying to add integration for my mod (Almost all the Ores) in JEI (show tooltips about my mod blocks), but when I try to add more than one line to the tooltip, the lines I add switch places as you can see on the video. It is probably me not knowing how to code, so maybe it is not the best place to post this. I am not sure what to do. Sorry for bothering you.

#### What happens:

https://drive.google.com/open?id=1V2oKuGJr5MddALvoZ-IksUSX-lExIa0O

#### What you expected to happen:

Show some readable information, not a never ending cycle of switching lines.

#### Steps to reproduce:

Look at a block that shows more than 1 line of tooltip.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.10.8-B72_1.15.2
- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.0

#### Possible Conflicting Mods (Provide their version, as well)

Almost all the Ores 2.0.2.0
Here's the source : 
https://github.com/waylanderou/almost-all-the-ores/tree/1.15.1
Hwyla plugin is located in /integration/hwyla/

**Comment by TehNut** [comment]
https://github.com/waylanderou/almost-all-the-ores/blob/a98ab867f6919691f24f711e337f98d1ec627631/src/main/java/waylanderou/almostalltheores/client/TooltipHandler.java#L226

`Set` is not ordered.

https://github.com/waylanderou/almost-all-the-ores/blob/a98ab867f6919691f24f711e337f98d1ec627631/src/main/java/waylanderou/almostalltheores/integration/hwyla/BlockInformationProvider.java#L21

Stop creating a new instance every frame.
