### ISSUE TITLE
Item Frames Show Framed Stack Rather Than Frame Stack

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#225]
When looking at a filled item frame, the tooltip shows the stack held by the frame, rather than the frame itself, creating a weird conflict of information. If the displayed stack is intended to be the contents, maybe the tooltip should instead show the name of the contents, with a sub-text stating "in Item Frame" etc.

**Version:** [fabric-1.15.2-1.9.20-71](https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2880088)

![Screenshot](https://i.imgur.com/S4du8eu.png)

**Comment by TehNut** [comment]
Intentional
