### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sscards55** [TehNut-Mods/HWYLA#239]
Option to disable all tooltips that HWYLA provodes.

**Comment by TehNut** [comment]
numpad 1

**Comment by sscards55** [comment]
That's not what I meant, I don't want to disable the GUI. I want to disable each individual tooltip provided, but I want an option for all tooltips provided.

**Comment by TehNut** [comment]
All additional data provided by Hwyla itself is already configurable. If a mod adds more data and don't provide a config, you need to go to them.
