### ISSUE TITLE
HWYLA Fabric does not have supported modloader tag

### ISSUE THREAD

**Issue by Peca21** [TehNut-Mods/HWYLA#241]
#### Issue Description:
HWYLA Fabric on twitch (curseforge) does not have supported modloader tag and because of that twitch app thinks its forge compatible and installs a fabric version of the mod even when you are running forge.

#### What happens:
1. Twitch app donwloads fabric version of HWYLA.
2. Game crashes or mod does not load

#### What you expected to happen:
1. Twitch app donwloads forge version of HWYLA.
2.Works fine

![Screenshot](https://user-images.githubusercontent.com/13818400/79370142-74b0a180-7f52-11ea-83ca-bfc7ee87255e.png)

**Comment by TehNut** [comment]
I'll mark it, but unless the twitch app finally changed something, it will download fabric regardless because it's newer.

**Comment by Peca21** [comment]
Yeah I just noticed that, I sent them a bug report for that.

**Comment by TehNut** [comment]
It is now marked
