### ISSUE TITLE
Fluids not being shown in the world 

### ISSUE THREAD

**Issue by Fruxiom** [TehNut-Mods/HWYLA#242]
I load up a new world with Hwyla installed with forge and water or lava isnt being shown just hte blocks beneath.

What you expected to happen:
For the tool tip to show water or lava not the block below

Affected Versions (Do *not* use "latest"): 1.12.2

- Hwyla: 1.12.2
- Minecraft: 1.12.2
- Forge: 1.12.2

![2020-04-21_21 14 23](https://user-images.githubusercontent.com/64103787/79909707-58f74080-8415-11ea-8fd1-6f012a32794a.png)

**Comment by TehNut** [comment]
Numpad 2 or enable directly in the config

**Comment by Fruxiom** [comment]
Thank you!
