### ISSUE TITLE
14.4 server crash during startup

### ISSUE THREAD

**Issue by Raghalin** [TehNut-Mods/HWYLA#243]
not sure if AATO or HWYLA problem, so I'm posting in both. 
But when inserted into a 14.4 server they crash during server start.

#### What happens:
during startup of server game CTD

#### What you expected to happen:
the game to load proerly

#### Steps to reproduce:
1.  removed all mods
2. added 1 mod to server folder, launched server
3.  if stable, see #2 if crash, report
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version ERROR}
- Minecraft: Minecraft Version ID: 1.14.4
- Forge: forge-1.14.4-28.2.4-universal.jar Forge {forge@28.2.4 DONE}

#### Possible Conflicting Mods (Provide their version, as well)

- Almost All The Ores : almostalltheores-1.0.3.2.jar Almost All the Ores {almostalltheores@1.0.3.2 DONE}

[crash-2020-04-23_07.21.39-server.txt](https://github.com/TehNut/HWYLA/files/4522508/crash-2020-04-23_07.21.39-server.txt)

**Comment by waylanderou** [comment]
It is a problem with AatO calling Minecraft.getInstance() server side. It will be fixed soon. The issue should be closed on this repository.
