### ISSUE TITLE
all pams seeds are wheat seeds to HWYLA

### ISSUE THREAD

**Issue by IchigoGames** [TehNut-Mods/HWYLA#244]
All pams seeds show up in HWYLA as Wheat seeds

#### Affected Versions (Do *not* use "latest"):

- Hwyla:Hwyla-forge-1.10.8-B72_1.15.2 
- Minecraft:1.15.2 
- Forge:31.1.50

#### Possible Conflicting Mods (Provide their version, as well)

pamhc2crops-1.15.2-1.0.3
![2020-04-29_12 16 37](https://user-images.githubusercontent.com/11888162/80625863-6747ec80-8a13-11ea-9099-a8be0dfa36c8.png)

**Comment by TehNut** [comment]
Pam issue
