### ISSUE TITLE
Furnace render order is weird

### ISSUE THREAD

**Issue by Darkhax** [TehNut-Mods/HWYLA#245]
#### Issue Description:
The render order of the special furnace info seems to have a weird render order. This is mainly noticeable on the text for an itemstack.

![image](https://user-images.githubusercontent.com/2250798/80678024-99a42900-8aa9-11ea-8e06-09c9c3676d1b.png)

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.10.8-B72_1.15.2
- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.60

#### Possible Conflicting Mods (Provide their version, as well)
No other mods installed

**Comment by TehNut** [comment]
https://github.com/TehNut/HWYLA/commit/e64ea9f07477e2a6eecf1242f1c9c13791800d31
