### ISSUE TITLE
Caught unhandled exception : [class mcp.mobius.waila.addons.core.HUDHandlerBlocks]

### ISSUE THREAD

**Issue by HendrikJ79** [TehNut-Mods/HWYLA#251]
#### Issue Description:
Clientside crashes after loading en logging in multiplayer world, also crashing after loading in a singleplayer world.

[WailaErrorOutput.txt](https://github.com/TehNut/HWYLA/files/4627994/WailaErrorOutput.txt)
[latest (compressed).log](https://github.com/TehNut/HWYLA/files/4628000/latest.compressed.log)

#### What happens:
Client crashing after loading of logging in to a world, before crashing it says Saving World.
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.9.22
- Minecraft: 20w18a, 20w19a, 20w20a, 20w20b, 20w21a
- Forge: None
- Fabric Loader: 0.8.2 Build 194 on 20w20b
- Fabric Api: 0.10.9 Build 346 on 20w20b

#### Possible Conflicting Mods (Provide their version, as well)
No conflicting mods found, client also crashes when disabling other mods.

**Comment by HendrikJ79** [comment]
Crash-report in Snapshot 20w21a

[crash-2020-05-22_02.18.26-client.txt](https://github.com/TehNut/HWYLA/files/4665402/crash-2020-05-22_02.18.26-client.txt)

**Comment by TehNut** [comment]
https://www.curseforge.com/minecraft/mc-mods/hwyla/files/2987120
