### ISSUE TITLE
Notice: 1.16 is fully released

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/HWYLA#259]
I'd like to just let you know 1.16 fully released today and the latest (Hwyla-fabric-20w13b-1.9.22-73.jar) snapshot on Curseforge is not compatible with the full release. It crashes on any world load due to classes needing to be renamed due to obfuscation. Thanks!

**Comment by ChloeDawn** [comment]
~~`Hwyla-fabric-20w13b-1.9.22-73.jar` is for Fabric mod loader, not Forge. It is listed as such on CurseForge. Please be patient, it will be updated for Forge 1.16 eventually.~~ Nvm I misinterpreted the comment.
