### ISSUE TITLE
Dead Maven

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [TehNut-Mods/HWYLA#266]
#### Issue Description:
The maven _http://tehnut.info/maven_ does not work.

#### What happens:
`java.net.UnknownHostException: tehnut.info`

#### What you expected to happen:
`Gradle build succesful`

#### Steps to reproduce:

1. add the following to your `build.gradle`:
```
repositories {  
    maven {url "http://tehnut.info/maven"}
}

dependencies {
    deobfCompile "mcp.mobius.waila:Hwyla:<HWYLA_VERSION>"
}
```
2. run gradle

____
#### Affected Versions:

all

**Comment by TehNut** [comment]
#253
