### ISSUE TITLE
Question: Where is the FORGE Version for MC v1.16 ?

### ISSUE THREAD

**Issue by SirTwsted** [TehNut-Mods/HWYLA#272]
I looked in Curseforge and red your red text that stated there are 2 versions, but there is not.
As I went through the files list for Minecraft Version v1.16
and it only lists fabric versions and not the forge version.

Its a shame that fabric split the community in two.

**Comment by TehNut** [comment]
I just haven't done it yet. There is #268 doing so, bit I haven't gotten a chance to pull and release.

> Its a shame that fabric split the community in two.

It's a shame users can't fuck off and let devs do what they want. If anything, it's Forge who split the community in 1.14+.

**Comment by SirTwsted** [comment]
Thats funny, because Forge team says it was Fabric.....LOL
ooh and telling users to fuck off just because they are butt hurt is very childish.  anyways, IDGAFAM.
