### ISSUE TITLE
[1.16.1] Redstone comparator/repeater tooltip doesn't work

### ISSUE THREAD

**Issue by ocram9** [TehNut-Mods/HWYLA#279]
#### Issue Description:
The tooltip from the redstone comparator and the redstone repeater don't work. It shows the ID instead of the actual tooltip.

#### Steps to reproduce:

1. Place a comparator/repeater
2. Look at it with hwyla
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.10.9-B76_1.16.1 forge
- Minecraft: 1.16.1
- Forge: 31.0.81

#### Modlist:
![Screenshot_12](https://user-images.githubusercontent.com/49008532/88659347-2ffde000-d0d5-11ea-919c-9f110866fe0c.png)

#### Screenshot:
![Screenshot_13](https://user-images.githubusercontent.com/49008532/88659324-270d0e80-d0d5-11ea-86c2-adbfa0a51987.png)

**Comment by TehNut** [comment]
#247
