### ISSUE TITLE
[1.16.1] Incompatibility with forge 31.0.93

### ISSUE THREAD

**Issue by ocram9** [TehNut-Mods/HWYLA#280]
#### Issue Description:
The game won't launch when hywla is installed (it doesn't crash, it just won't launch).

#### Steps to reproduce:

1. Install hwyla and forge 31.0.93
2. Start the game

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: forge-1.10.9-B76_1.16.1.jar
- Minecraft: 1.16.1
- Forge: 31.0.93

#### Possible Conflicting Mods (Provide their version, as well)
![Screenshot_12](https://user-images.githubusercontent.com/49008532/88659781-e5309800-d0d5-11ea-9be6-0cfbf2d2d074.png)

#### Screenshot:
![Screenshot_14](https://user-images.githubusercontent.com/49008532/88659794-eb267900-d0d5-11ea-8ca1-1f5c89ff6c92.png)

**Comment by TehNut** [comment]
Downgrade forge, they made a change that breaks literally every mod.

**Comment by pupnewfster** [comment]
31.0.93 actually "reverted" the license string being required from the mods.toml file. This crash/error is the other breaking change that was made, and only is causing Hwyla to crash because it (Hwyla) is registering the listener for `RegisterCommandsEvent` on the wrong event bus (mod event bus versus forge event bus)

**Comment by ocram9** [comment]
I completely forgot to add the log, sorry about that. The latest log: https://gist.github.com/ocram9/faefbb1f4dc0b859e4c46df1e73a7974

**Comment by 04Slash** [comment]
Downgrading to forge 32.0.88 should fix this issue. Any newer version will not work currently. As of this comment, the latest version is 32.0.96.
Edit: 97 is still broke, stick to 88.
