### ISSUE TITLE
[1.16.1] Crash on startup

### ISSUE THREAD

**Issue by JaisDK** [TehNut-Mods/HWYLA#281]
#### Issue Description:
Crash on startup

#### What happens:

https://gist.github.com/JaisDK/7faeb5088d252754727744b83bc94d52

#### What you expected to happen:

Not crash

#### Steps to reproduce:

Looks to be the same error as #280
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.10.9-B76_1.16.1
- Minecraft: 1.16.1
- Forge: 32.0.93

**Comment by TehNut** [comment]
If you're aware it's a duplicate, don't make a new issue...
