### ISSUE TITLE
Missing Fabric version tag on CF for 1.9.23-79

### ISSUE THREAD

**Issue by tyra314** [TehNut-Mods/HWYLA#293]
#### Issue Description:
Please add the Fabric version tag to file on curseforge, it is missing for the latest upload. Thanks.

#### Affected Versions (Do *not* use "latest"):

Link to CF file:

https://www.curseforge.com/minecraft/mc-mods/hwyla/files/3033613

**Comment by TehNut** [comment]
Done, thanks
