### ISSUE TITLE
Doesn't work with Wurst hacked client

### ISSUE THREAD

**Issue by ShadowWalker12** [TehNut-Mods/HWYLA#311]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Kill aurora causes it to crash 

#### What you expected to happen:
work normal

#### Steps to reproduce:

1. install wurst hacked client
2. Turn on kill aurora
3.  get near mob
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 
- Minecraft: 
- Forge:

**Comment by UpcraftLP** [comment]
That's great!

**Comment by keraldi** [comment]
It's not a bug, it's a feature.

Also, your issue template is not filled out.

**Comment by TehNut** [comment]
Working as intended. Thank you for the chuckle.
