### ISSUE TITLE
[1.11] IMC mod ID is case sensitive

### ISSUE THREAD

**Issue by squeek502** [TehNut-Mods/HWYLA#33]
Just wanted to note that IMC's that use "Waila" will have to update to "waila" in 1.11. Not sure if this is something that should be fixed in FML/Forge, or if it's just something to keep in mind when porting, but it might be worth adding a note somewhere in the 1.11 readme about it?

**Comment by TehNut** [comment]
I figured it would be obvious since Forge enforces lowercase modid's now. Perhaps Forge should log an error if an IMC is sent with a non-lowercase modid?

**Comment by TehNut** [comment]
c5b1ff27407d222d7060f8ffdb61026934a43db5

**Comment by squeek502** [comment]
Yeah, I was just not expecting it as it doesn't seem to make sense for Forge to both enforce lowercase mod IDs *and* do case-sensitive lookups. Just thought I'd mention it. 👍
