### ISSUE TITLE
Crash looking at chameleon multi-storage chest

### ISSUE THREAD

**Issue by shortybsd** [TehNut-Mods/HWYLA#34]
Forge 2199
MC v1.11
shetiphiancore-1.11.0-3.4.1
multistorage-1.11.0-1.3.0
Hwyla-1.8.5-B19_1.11

When looking at a chameleon multi-storage Hwyla/Waila crashes the client. Disable Hwyla and everything is fine. Here is the error:
http://pastebin.com/KbQDZ3Xr

**Comment by TehNut** [comment]
Caused by Multistorage returning null in `BlockStorageType#getPickBlock(...)`. Please report this to them.

Relevant code:

```java
    public ItemStack getPickBlock(IBlockState state, RayTraceResult target, World world, BlockPos pos, EntityPlayer player) {
        BlockStorageType.EnumType type = getEnumType(state);
        switch (BlockStorageType.1.$SwitchMap$shetiphian$multistorage$common$block$BlockStorageType$EnumType[type.ordinal()]) {
            case 1:
            ...
            case 16:
                return new ItemStack(this, 1, 6);
        }
        return null;
    }
```

**Comment by TehNut** [comment]
Adding a fallback with intrusive, yet protective behavior.

![img](http://i.imgur.com/ETHUYjx.png)

**Comment by shortybsd** [comment]
Thank you sir, I wasn't for sure who was at blame but will inform the other developer. Thanks for the fast response and thanks for being a great developer that you are!
