### ISSUE TITLE
Looking at a block in the nether with xaeros world map causes the screen to flash orange and black

### ISSUE THREAD

**Issue by TheCorruption** [TehNut-Mods/HWYLA#35]
Tested on the newest versions of both mods.

**Comment by TehNut** [comment]
What version of MC? I need specific numbers for all 3.

**Comment by TheCorruption** [comment]
It happens on 1.10.2 with Hwyla-1.8.1-B13 and XaerosWorldMap-b1.7.1

**Comment by TehNut** [comment]
Should be fixed on latest.
