### ISSUE TITLE
1.8.7 B21 breaks compatibility with other WAILA mods

### ISSUE THREAD

**Issue by darkphan** [TehNut-Mods/HWYLA#40]
#### Issue Description:

Version 1.8.7 B21 breaks compatibility with other mods that depend on WAILA (WAILA Harvestability), WAWLA, etc

#### What happens:

Other WAILA dependent mods are not able to interact with WAILA

#### What you expected to happen:

Other mods to be able to interact with HWYLA

#### Steps to reproduce:

1. Install latest HWYLA
2. Install WAWLA
3. Observe as WAWLA renders its own text in the upper left since it does not detect WAILA
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.7 B21
- Minecraft: 1.10.2
- Forge: 12.18.3.221

**Comment by TehNut** [comment]
...did I cherry-pick the wrong commit?

Edit: I fucking did I'm an idiot. https://github.com/TehNut/HWYLA/commit/ee6068fee81d70229cd22c878ccf858e5521d1f3#diff-11b38ab89830f9235e330a65c2c58b36R35

**Comment by darkphan** [comment]
At least it was an easy fix :D
