### ISSUE TITLE
Crash when looking at RS drives.

### ISSUE THREAD

**Issue by darkmdbeener** [TehNut-Mods/HWYLA#42]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

skyblock 3.0.6

#### What happens:
when looking at a Refined Storage drive on a server you will crash out.

#### What you expected to happen:

not to crash

#### Steps to reproduce:

1. set multiple drives 
2. put in some disks into one
3. look at them 
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.8-b22_1.10.2
- Minecraft: 1.10.2
- Forge: 12.18.3.2215

https://u.nya.is/uldukh.log

#### Possible Conflicting Mods (Provide their version, as well)

wawla (happens with it turned removed.)

**Comment by TehNut** [comment]
Try with this build and increase the value of `waila.cfg.nbtnetworklimit` to something like `5000000`. There's not really a reason for anything to reach a *2mb* NBT tag, but sure, whatever.

This is only needed on the client, as this is a deserialization issue on the clientside of the packet.

http://tehnut.info/share/Hwyla-1.8.8-BCUSTOM_1.10.2.jar

**Comment by darkmdbeener** [comment]
I am not op, we were on darkosto sub server when this started happening. The change you are calling for should this be done server side (the limit not the .jar)

**Comment by TehNut** [comment]
As I said, this is a clientside deserialization issue. Not a server issue.

**Comment by darkmdbeener** [comment]
nvm i found it had to start it up to get the option to change.

**Comment by darkmdbeener** [comment]
does not seem to stop the getting kicked part going to see if it still causes a kick on a new server.

It may not be hwyla (or even wawla) since removing both I still get kicked or it could have caused it and i am stuck crashing for the time being.

**Comment by TehNut** [comment]
Alright I'm going to try something else for this.

**Comment by TehNut** [comment]
Try this build. No configuration needed. Using a different deserialization method.

http://tehnut.info/share/Hwyla-1.8.8-BCUSTOM_1.10.2.jar

Also, you can close the issues on the other repos.

**Comment by darkmdbeener** [comment]
testing it now, though its the same name and link as the previous one. Did you override it?

Edit: 

A fatal error has occurred, this connection is terminated.

Edit:

https://u.nya.is/rrknsp.log
log file

**Comment by darkmdbeener** [comment]
got it set up to see if it will crash on a new server once i have a large nbt and if the crashing was just something left over from the old mod version.

**Comment by darkmdbeener** [comment]
The crashes I am experiencing now may not be related to this mod, the changes you did might have fixed this issue. We have another issue put in for another mod. That being said I am still testing it on the test server to see if this mod does crash on another server..

https://github.com/gr8pefish/IronBackpacks/issues/148

**Comment by darkmdbeener** [comment]
let a farm run all night to fill a rs system with items that would have a lot of nbt data and it has not crashed on me. I did notice the chickens mod and hatchery mod does not show all the info when looking at a chicken but if this fix is took care of the crash ill make a issue report with them.

**Comment by TehNut** [comment]
Sweet thanks for getting back to me

**Comment by darkmdbeener** [comment]
Thank you for working fast on getting this fixed.

**Comment by TehNut** [comment]
Builds are now available on Curse for both 1.10 and 1.11

**Comment by darkmdbeener** [comment]
I will alert them thank you very much.

**Comment by scerion** [comment]
Greetings, I updated to this version of the mod since having the above problem raoulvdberge linked to, and since updating I can no longer see the names of the Chickens in the Hatchery Nests.

**Comment by TehNut** [comment]
Please create a new issue and provide any relevant log information available.
