### ISSUE TITLE
1.11.2 Crash - WailaSplitter

### ISSUE THREAD

**Issue by MisterShawn** [TehNut-Mods/HWYLA#43]
#### Issue Description:
(Technically it's a mod pack, but it's a personal one and I'm the author.)
Game crashes in single player when looking at a block.
Log: http://pastebin.com/raw/weYdAqBS
____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.9-B22_1.11
- Minecraft: 1.11.2
- Forge: 13.20.0.2226

**Comment by TehNut** [comment]
...but... it's there... https://github.com/TehNut/HWYLA/blob/80e52d0bda317039b6d4f603073f8a9c31d34433/src/main/java/mcp/mobius/waila/api/SpecialChars.java#L38-L38

**Comment by TehNut** [comment]
I'm unable to reproduce this using just Forge 2226 and Hwyla.

**Comment by MisterShawn** [comment]
I created a new world and now it works fine. No idea what happened. Sorry to bother you. :)
