### ISSUE TITLE
A lot of NPE's in latest build

### ISSUE THREAD

**Issue by Eufranio** [TehNut-Mods/HWYLA#44]
Just updated my HWYLA, and it started throwing a lot of NPE's to the console. I could write the error here but it's best in hastebin: https://hastebin.com/mevocipeni.sql

Versions:

- Hwyla: 1.10.2-1.8.9B23
- Minecraft: 1.10.2
- Forge: 12.18.3.2202

My modpack: http://www.technicpack.net/modpack/magibeta-pack.940049

**Comment by TehNut** [comment]
Caused by TechReborn. @ProfessorProspector wat r u doin m8

**Comment by Prospector** [comment]
Are you on the latest version of TR?

**Comment by Eufranio** [comment]
Yes, I am. I updated all my mods (including Hwyla & TR) today, when it started giving the errors.
(You can see the versions [here](http://www.technicpack.net/modpack/magibeta-pack.940049/mods).)

**Comment by Prospector** [comment]
Alright. Can you make an issue over on the TechReborn repo so we're not spamming HWYLA?

**Comment by Eufranio** [comment]
Sure it's TechReborn? https://github.com/TehNut/HWYLA/issues/46

**Comment by TehNut** [comment]
Yes.
