### ISSUE TITLE
[1.10.2] Conflict with JustEnoughTooltips, breaking it's secondary hotkeys on a held item when focusing a world block/tile, but not entities

### ISSUE THREAD

**Issue by Kiefy** [TehNut-Mods/HWYLA#45]
Posted on [JET's Issue Tracker](https://github.com/superckl/JustEnoughTooltips/issues/9). Thought you should know.

**Comment by TehNut** [comment]
This is just a limitation of Minecraft's keybind system. You'll have to change one of the mod's keybinds.
