### ISSUE TITLE
[1.8.9-B22_1.11] tick crash?

### ISSUE THREAD

**Issue by kreezxil** [TehNut-Mods/HWYLA#47]
I don't know what the player on my server did to cause this, they didn't even know.

https://github.com/Minecolonies/minecolonies/issues/544

**Comment by TehNut** [comment]
Why the hell do you think that is me? This doesn't even reference Hwyla. I never even subscribe to that event.

**Comment by kreezxil** [comment]
sorry, I gave the wrong paste.

here is the correct paste

http://pastebin.com/97n7WN3V

**Comment by TehNut** [comment]
This looks like somebody is giving me a null stack which is not my problem
