### ISSUE TITLE
Actually Additions plants show as strange items

### ISSUE THREAD

**Issue by Ricket** [TehNut-Mods/HWYLA#49]
![image](https://cloud.githubusercontent.com/assets/196978/22676968/fbdca798-ecbc-11e6-88a9-eedb8e29d96a.png)

![image](https://cloud.githubusercontent.com/assets/196978/22676990/34be891e-ecbd-11e6-9ba6-557b4c061bb0.png)

Modpack: Direwolf20-1.10 v1.4.1
HWYLA: Hwyla-1.8.9-B23_1.10.2
Actually Additions: ActuallyAdditions-1.10.2-r98

**Comment by IamAlathe** [comment]
I have also noticed this.  I'm not playing on a modpack, just something I've put together myself.  They used to show up correctly, and I'm not sure when it changed.  I am playing on 1.11.2.

Actually Additions-1.11.2-r100 (But I know it was also doing it on r99)
Hwyla-1.8.9-B22_1.11
WailaHarvestability-mc1.11-1.1.9 (Just in case that could be related to the issue)

**Comment by TehNut** [comment]
Crops display their output item. This was changed to match Waila's handling of Vanilla. (ie wheat seeds -> wheat)

You can toggle `Modules > VanillaMC > Alternate Crop` if you don't like it.

**Comment by IamAlathe** [comment]
There is still an error, then.  While flax does indeed output string, canola does not out put paper cones.  It outputs canola and canola seeds.  "String" I can live with, but the label of "paper cone" is just strange.  A paper cone is an item from AA but it must be crafted with paper, and has nothing to do with canola.

**Comment by TehNut** [comment]
Well, I am calling `getCrop()` so I'm not too sure how it could be on my side.

**Comment by Ricket** [comment]
Hm, I see the logic but I'm glad it is a config option. I can see that it's useful, but then shouldn't cows be shown as "raw beef" and stone as "cobblestone"?

I opened a bug about the paper cone issue.

**Comment by Ricket** [comment]
@TehNut , please check out the ActuallyAdditions issue. Ellpeck is using one item as a "miscellaneous" item and apparently the paper cone is the 0'th such item. Perhaps the two of you could compare notes and figure out which side is "at fault".
