### ISSUE TITLE
Looking at Ender Chest doesn't show its color pattern

### ISSUE THREAD

**Issue by Ricket** [TehNut-Mods/HWYLA#51]
I think this is a regression from WAILA. I'm pretty sure WAILA would show the three colors of the ender chest, but HWYLA does not seem to do that.

![image](https://cloud.githubusercontent.com/assets/196978/22815755/adbcd364-ef2b-11e6-8141-14f1a466e53a.png)

I expected the tooltip to show "Yellow/Black/Yellow".

Hwyla-1.8.9-B23_1.10.2
EnderStorage-1.10.2-2.2.0.96-universal

**Comment by TehNut** [comment]
I removed all third party plugins because they were completely reflection which is very slow. Ask EnderStorage to re-implement.
