### ISSUE TITLE
HWYLA Doesn't show channels used when looking at ME Smart/Dense Cables

### ISSUE THREAD

**Issue by Xiaminou** [TehNut-Mods/HWYLA#57]
HWYLA Doesn't show channels used when looking at ME Smart/Dense Cables.

- Hwyla: 1.8.11-B24_1.11
- Minecraft: 1.10.2
- Forge: 2254

**Comment by TehNut** [comment]
Hwyla doesn't add compat for 3rd party mods. Ask AE to add it.
