### ISSUE TITLE
[1.11.2] Integration with Storage Drawers like WAILA

### ISSUE THREAD

**Issue by NovaViper** [TehNut-Mods/HWYLA#60]
#### Issue Description:
Could it possible to add support for [Storage Drawers ](https://minecraft.curseforge.com/projects/storage-drawers)so you can see how filled up the drawer is and what and how many items are inside each draw slot? Basically, add the the support that WALIA had for Storage Drawers

**Comment by TehNut** [comment]
This is on Storage Drawers to add. They probably forgot to lowercase the modid for the IMC message.

**Comment by NovaViper** [comment]
Thanks, I just posted the issue on their issue tracker
