### ISSUE TITLE
Doesn't show furnance information

### ISSUE THREAD

**Issue by NovaViper** [TehNut-Mods/HWYLA#61]
#### Issue Description:
When looking at a furnace, the information about the furnace pops up like normal, but when it is smelting, I can see the arrow but it is blank for the what is being smelted and what's the output

#### Steps to reproduce:

1. Place a furnace
3. Place fuel and smelting item inside
2. Look at the furnace

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.12
- Minecraft: 1.11.2
- Forge: 13.20.0.2228

**Comment by TehNut** [comment]
Yeah I cleaned a little too much recently.

**Comment by NovaViper** [comment]
Yeah, I felt it was quite strange when I saw this
