### ISSUE TITLE
Black box around sun/black sky when HWYLA info box pops up

### ISSUE THREAD

**Issue by jakey1995abc** [TehNut-Mods/HWYLA#63]
#### Issue Description:
Whenever I look at a block the sun will turn black, or if I am using a resource pack the whole sky will turn black. This only occurs when the information box for blocks, items, etc is enabled.

#### Affected Versions (Do *not* use "latest"):
- Hwyla: Hwyla-1.8.12-B25_1.11.jar
- Minecraft: 1.11.2
- Forge: 13.20.0.2265

#### Possible Conflicting Mods (Provide their version, as well):
Based on previous similar issues that other users have reported, it may be caused by the journeymap-1.11.2-5.4.6.jar mod.

**Comment by leagris** [comment]
Confirm same here.
![visual glitch](https://cdn.discordapp.com/attachments/263684147078365184/300724478520983562/output_HMOrxc.gif)

**Comment by jakey1995abc** [comment]
I guess this mod is dead :( oh well, the latest version beats a version which would crash the game xD

**Comment by TehNut** [comment]
Not dead. I just haven't had time to fix it. It requires rewriting *all* the rendering code to use `GLStateManager` instead of raw `GL11` calls.

**Comment by TehNut** [comment]
Does this still occur in the latest release?

**Comment by TehNut** [comment]
No response in over a month. Considering fixed.
