### ISSUE TITLE
[Suggestion] Support for EnderStorage

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/HWYLA#64]
It’d be great if you could see how much liquid there’s in an EnderStorage ender tank.

**Comment by TehNut** [comment]
I'll re-enable the fluid and power caps. But to be clear, this isn't ES compat, this is generic fluid compat

**Comment by ghost** [comment]
@TehNut You can see how much fluid there is in tanks from other mods, like the fluid tank from Ender IO or the seared tank from Tinkers’ Construct, but you can’t with EnderStorage’s ender tank.

**Comment by TehNut** [comment]
They add that themselves. This would support the fluid cap. So any tank properly implemented
