### ISSUE TITLE
Crash in picking SCM block - does not occur without HWYLA

### ISSUE THREAD

**Issue by dshadowwolf** [TehNut-Mods/HWYLA#67]
#### Issue Description:
Crash in removing a Super Circuit Maker circuit when HWYLA is installed

#### What happens:
NPE in SCM as code comes through HWYLA

#### What you expected to happen:
No NPE

#### Steps to reproduce:

1. Install WAILA/HWYLA
2. Install SCM
3. Make SCM circuit
4. Break SCM circuit plate

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.13-B27
- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Super Circuit Maker: 1.0.4

#### Possible Conflicting Mods (Provide their version, as well)
Super Circuit Maker - version is above

(This is for reference - the actual error likely lies with SCM not implementing a method properly - see [SCM issue 309](amadornes/SCM-Localization-Issues#309))

**Comment by TehNut** [comment]
#53
