### ISSUE TITLE
Blocks without an Item don't show up in the HUD

### ISSUE THREAD

**Issue by Darkhax** [TehNut-Mods/HWYLA#68]
#### Issue Description:
If you look at any block which doesn't have an ItemBlock, such as lit redstone ore, the hud will not show. 

#### What happens:
Instead of having a hud be visible, there is no hud. I suspect this is because the ItemStack doesn't have an Item, and is considered empty.

#### What you expected to happen:
I expect the hud to show up, using the block as a fallback, or having some built in code to allow blocks without items to fall back to those. 

#### Steps to reproduce:
1. Place down redstone block.
2. If it's not lit, punch or walk on it.
3. Look at the hud and be disapointed.

#### Affected Versions (Do *not* use "latest"):
- Hwyla: Latest :kappa: (1.8.13)
- Minecraft: 1.11.2
- Forge: 13.20.0.2314

#### Possible Conflicting Mods (Provide their version, as well)
Nope

**Comment by TehNut** [comment]
STOP WASTING MY TIME REEEEE

![reeee](https://media.giphy.com/media/IyvPPs3A5c96U/giphy.gif)

**Comment by Darkhax** [comment]
Worst mod dev ever

**Comment by TehNut** [comment]
I may have reee'ed too soon.

**Comment by WenXin20** [comment]
It looks like this might be an issue again in 1.12 and 1.14.

Blocks without it's corresponding item won't display any info for the block.
This can be replicated with the mods Ceiling Torch and/or Tombstone. Ceiling Torches and Graves placed after a player death won't display any information. 
Corail31/tombstone_lite#107


If a new issue needs to be opened, just let me know!

**Comment by TehNut** [comment]
Mods can register a plugin that provides an override stack for their block.

https://github.com/TehNut/HWYLA/blob/048e1e33ffd747053945666ff202b94a8b9266be/src/main/java/mcp/mobius/waila/api/IRegistrar.java#L26-L34

**Comment by WenXin20** [comment]
Nice, thanks! I'll let them know.

**Comment by ghost** [comment]
@TehNut is it really done to differenciate blocks using the same class (and having the same tileentity), or i missed something ? hm yes, the accessor, sorry ;)
