### ISSUE TITLE
Narration on

### ISSUE THREAD

**Issue by Zygus42** [TehNut-Mods/HWYLA#70]
#### Issue Description:
The block you're looking at is being narrated - presumably to assist vision-impaired people, but can't turn it off and have it stay off.  Tried to turn it off under Mod Options/Waila/configs/waila/Narrate Blocks, and says it stays OFF, but voice continues.

#### Affected Versions (Do *not* use "latest"):
- Hwyla: 1.8.16-B30_1.12.jar
- Minecraft: 1.12
- Forge: forge-1.12-14.21.0.2322

#### Possible Conflicting Mods (Provide their version, as well)
Only HWyla & JEI installed.

**Comment by TehNut** [comment]
Already fixed and waiting to be released. #69
