### ISSUE TITLE
[1.12] Crash when opening "Controls" Menu

### ISSUE THREAD

**Issue by level555** [TehNut-Mods/HWYLA#71]
#### Issue Description:
Minecraft crashes when attemting to to open the Controls menu in minecrafts settings

#### What happens:

Game crashes

#### What you expected to happen:

Controls menu opens

#### Steps to reproduce:

1. Create minecraft 1.12 instance with forge and HWYLA
2. Launch minecraft
3. Click "Options..."
4. Click "Controls..."

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.17-B31_1.12
- Minecraft: 1.12
- Forge: 14.21.0.2322

#### Possible Conflicting Mods (Provide their version, as well)
No other mods installed
[crash-2017-06-13_22.24.38-client.txt](https://github.com/TehNut/HWYLA/files/1072806/crash-2017-06-13_22.24.38-client.txt)

**Comment by TehNut** [comment]
This is caused by Mojang adding a new `Map<String, Integer` field to `KeyBinding` for categories. I'll do a temporary fix with a magic number to *try* to avoid conflicting with other mods doing the same temporary fix.
