### ISSUE TITLE
Frame rate loss while looking at blocks

### ISSUE THREAD

**Issue by Nortrix0** [TehNut-Mods/HWYLA#74]
#### Issue Description:
I receive massive frame rate drops when using 1.8.17-B31_1.12 while looking at blocks or mobs.  The output log states that "root" and "root.tick" are taking too long, between 200 and 1000 ms.

This only seems to happen with 1.8.17-B31_1.12, as I tried downgrading to 1.8.16-B30_1.12 and did not get the lag

#### What happens:
When I look at blocks, whether the hud is on or off, my frame rate will go from 60 to 3-9.  As soon as I look away from the block, it goes back to 60fps.

#### What you expected to happen:
Not to lose over 50 frames just to look at details of blocks.

#### Steps to reproduce:

1. Install Hwyla-1.8.17-B31_1.12
2. Open either a Single Player world or a Realms world (Haven't tried a regular Multiplayer world, but I imagine it will also do this)
3. Look at the ground
4. Wait a few seconds to a minute
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.17-B31_1.12
- Minecraft: 1.12
- Forge: 14.21.0.2324
- LiteLoader: 1.12-SNAPSHOT

#### Possible Conflicting Mods (Provide their version, as well)
LiteLoader: 1.12-SHAPSHOT
VoxelMap: 1.6.22
JEI: 4.6.0.61
Just Enough Resources: 0.7.0.10
Wawla: 2.5.236

**Comment by TehNut** [comment]
#73
