### ISSUE TITLE
Crash On Dedicated Server

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#77]
Server crashes during world load.
No crash report was generated so the server log has been provided instead.

`java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag`

**Mod version:** [1.8.19-B33](https://minecraft.curseforge.com/projects/hwyla/files/2443649)
**Forge version:** [1.12-14.21.1.2387](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt)

**Server log:** [gist/d90f6c739adf04155748734ca31d4851#L2184](https://gist.github.com/InsomniaKitten/d90f6c739adf04155748734ca31d4851#file-fml-junk-earlystartup-log-L2184)

**Comment by TehNut** [comment]
Drunk told me I fixed this >.>
