### ISSUE TITLE
Chisels and Bits crash with HWYLA

### ISSUE THREAD

**Issue by kaosjr** [TehNut-Mods/HWYLA#78]
#### Issue Description:

Game crashes when placing a Chisels and Bits cover on a refined storage cable.

#### What happens:

The client crashes, forcing you to disable HWYLA to remove the offending block so you don't crash again.

#### What you expected to happen:

The game to work properly and not crash.

#### Steps to reproduce:

1. Create a chisels and bits cover by cutting any block vertically 3 times.
2.  Put a refined storage cable on the ceiling.
3.  Attempt to place the chisels and bits cover on the cable.
4. Client crashes.
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.15-B29_1.11
- Minecraft: 1.11.2
- Forge: 13.20.1.2388
- Modpack: Potentiality Version 2.0.1 (I've contacted the pack author, MiningMark48, as I know him fairly well, and he told me to report the bug to you.)

#### Possible Conflicting Mods (Provide their version, as well)

Refined Storage: 1.4.18
Chisels and Bits: 13.11
MCMultipart: 2.0.2

Crashlog is attached.
[crash-2017-07-04_21.28.49-client.txt](https://github.com/TehNut/HWYLA/files/1123526/crash-2017-07-04_21.28.49-client.txt)

**Comment by TehNut** [comment]
Dunno why he sent you here. Not on my end.
