### ISSUE TITLE
[1.11.2] 1.8.15-B29 Possible bug with translations?!

### ISSUE THREAD

**Issue by B0bbyD0llar** [TehNut-Mods/HWYLA#79]
#### Issue Description:
When I look at a fruit in the tree I get the English name displayed. The designation in the inventory is however properly localized (in my case German).

#### What happens:
It shows a non localized name of the fruit.

#### What you expected to happen:
Get the localized name of the fruit.

#### Steps to reproduce:

1. Simply take a look a fruit (from Pams Harvestcraft) hanging on a tree.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.15 B29
- Minecraft: 1.11.2
- Forge: 13.20.1.2393
- Pam's Harvestcraft 1.11.2h

#### Screenshoots

https://picload.org/image/rpcacala/fruitattree.png
https://picload.org/image/rpcacalr/fruitatinventar.png

**Comment by TehNut** [comment]
If it works properly for other blocks, this would be 100% on Pam's side.

**Comment by TehNut** [comment]
No response in almost 2 weeks. Considering non-issue.
