### ISSUE TITLE
[1.11.2] Errors, lag and console spam when looking at Not Enough Wands illumination wand lights

### ISSUE THREAD

**Issue by cragrim** [TehNut-Mods/HWYLA#81]
#### Issue Description:
When looking at Illumination Wand lights from Not Enough Wands the client lags and the console is filled with tooltip errors. This is not related to WailaHarvestability.
The console quickly gets overflowed and the log gets several MB big. This makes debugging difficult unless caught in the act. As you play the log file gets larger and larger and causes additional slowdowns.

#### Gif animation
http://i.imgur.com/EsqPPjh.gif
![Gif video](http://i.imgur.com/EsqPPjh.gif)

#### Error log 
Looking at the block
https://paste.ee/p/34s1J

Error log from looking at the block without OptiFine and Foamfix
https://paste.ee/p/pFslr

#### What happens:
Lag and console tooltip errors.

#### What you expected to happen:
Nothing.

#### Steps to reproduce:

1. Place light with Illumination Wand
2. Look at the light
3. See error.

____
#### Affected Versions (Do *not* use "latest"):
- Hwyla: Hwyla-1.8.17-B31_1.11.jar
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.1.2391
- Not enough wands: notenoughwands-1.1x-1.5.5.jar

#### Possible Conflicting Mods (Provide their version, as well)
I tried without the usual suspects OptiFine and FoamFix but it appears to be a conflict with some other mods. Still happens the same without them.

**Complete mod list:**
https://paste.ee/p/sIeiF

#### I made a post at Waila Harvestability before but issue persists without that mod so I closed that issue.
https://github.com/squeek502/WailaHarvestability/issues/58

**Comment by cragrim** [comment]
Also happens with extrautils2 Moonstone ore so the fault is not on Not Enough Wands side.

Gif animation:
![Moonstone error](http://i.imgur.com/5mygW0P.gif)

Console error log:
https://paste.ee/p/EICKU

**Comment by TehNut** [comment]
Looks more related to FTBLib than anything else.

**Comment by TehNut** [comment]
This was fixed in [this](https://github.com/LatvianModder/FTBLib/commit/1a6a5a7b8c7df5a1b96d319a2eaee829ef1b2ba3#diff-675f957c3e122bcbfcb3387f9f942fdfR15) commit on FTBLib. It doesn't seem that it's been published yet.

**Comment by cragrim** [comment]
Thank you! I will try it out as soon as its available.

EDIT: Looks like ftblib for 1.11.2 havent been updated in quite a while. 
https://minecraft.curseforge.com/projects/ftblib/files

**Comment by cragrim** [comment]
For future reference if you have this issue this is how you solve it for 1.11.2

Edit the config in the local folder in your client and locate:
**minecraft\local\client_config.json**
Change ftblib settings for **Item Ore Names** to false i.e.:
**"item_ore_names": false**

Cheers!
