### ISSUE TITLE
NullpointerException spam after placing down item from a mod.

### ISSUE THREAD

**Issue by Lordician** [TehNut-Mods/HWYLA#82]
#### Issue Description:
This is an issue i posted over at Rustic before i found out it was being caused by HYWLA and Rustic.
(https://github.com/the-realest-stu/Rustic/issues/67)
The issue is a particular bad spamming of nullpointer exceptions when i placed down the Brewing Barrel.
While this does not cause direct issues nor crashes, i fear this might impact performance and it makes it hard for me to read a server log due to it spamming the exception multiple times in a second.
This issue is not present when i try the same with WAILA (1.7.1_1.11.2).

#### What happens:
After placing the brewing barrel, nullpointerexceptions fill up the log.

#### What you expected to happen:
No exceptions.

#### Steps to reproduce:

1.  Install rustic-0.3.12 & Hwyla-1.8.17-B31_1.11
2. Load existing or new world
3. Place down Brewing Barrel
4. Watch your log getting spammed by the same exception.

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.17-B31_1.11
- Minecraft: 1.11.2
- Forge: 1.11.2-forge1.11.2-13.20.1.2414

#### Possible Conflicting Mods (Provide their version, as well)
- Rustic: rustic-0.3.12

**Comment by TehNut** [comment]
He is returning a `null` `IFluidHandler` after saying he does have one. 100% on his side.
