### ISSUE TITLE
No theme options?

### ISSUE THREAD

**Issue by sweetsosweet** [TehNut-Mods/HWYLA#85]
#### Issue Description:
In previous versions, when you chose Format Content, there was an option to change the theme, but I don't see that button anymore. Has the option been removed? Or is it somewhere else now?

#### What happens:
No button.

#### What you expected to happen:
A button.

#### Steps to reproduce:

1. Numpad 0 - open options
2. Click "Waila"
3. Click "Format content"
4. Search for button to change to other themes
5. Be disappointed
6. Proceed to copy-paste colors manually instead...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.12-1.8.19
- Minecraft: 1.12
- Forge: 14.21.1.2443

#### Possible Conflicting Mods (Provide their version, as well)
???????

**Comment by TehNut** [comment]
er... It's there. Just invisible. I'll take a look. It works if you click the blank space under the `Text Color` field.
