### ISSUE TITLE
[Feature request] Thermal Dynamics integration

### ISSUE THREAD

**Issue by Kilmatar** [TehNut-Mods/HWYLA#87]
Is it possible to add integration with Thermal Dynamics fluiducts/fluxducts?
In MK 1.7.10 WAILA was able to show actual ducts filling (how many RF stored in fluxducts or how many fluid is in fluiducts). Is it possible to return this back for MK 1.12?

**Comment by TehNut** [comment]
Their end.

**Comment by Kilmatar** [comment]
I was open ticket for here and you close ticket with remark "Their end".
I open ticket https://github.com/CoFH/Feedback/issues/522 
and KingLemming close with remark about "WAILA's end"!

C'mon guys. Please - talk with each other and resolve this problem. Please!

**Comment by TehNut** [comment]
This *was* done on Wailas end very poorly using reflection. I have since taken the same stance as JEI in that mods add compat on their own. 

I will not be adding anything for this.
