### ISSUE TITLE
[1.12.1] Horizontal Blocks Show Wrong Item Name/ID

### ISSUE THREAD

**Issue by Darkosto** [TehNut-Mods/HWYLA#88]
#### Issue Description:
When looking at block data in HWYLA, horizontal logs show the incorrect item name and a broken texture for the icon.

#### What happens:
Name shows incorrectly

#### What you expected to happen:
I expected Oak to be the name/image

- Hwyla: 1.8..20-B35_1.12
- Minecraft: 1.12.1
- Forge: 2474

![image](https://user-images.githubusercontent.com/10309699/30227995-d38cb6ee-94a9-11e7-9a89-ddcf1a54ace7.png)

Thank you!
Darkosto

**Comment by TehNut** [comment]
If you pick-block that, do you get the proper item? Could you also run `/dumphandlers` and put the resulting file on Gist?

**Comment by Darkosto** [comment]
Pick block gives the proper item "Oak Wood"

https://gist.github.com/Darkosto/335f85ffb9e6a9c0178135ed8e415ed3

![image](https://user-images.githubusercontent.com/10309699/30232221-b43b61ce-94bc-11e7-92d0-b6c29275ff26.png)

**Comment by TehNut** [comment]
~~And uh... The result of `/dumphandlers`?~~

I thought I clicked on the link, but I clicked on the image. 

![](https://media.tenor.com/images/fa7be96565d6a62208b61497b92576b7/tenor.gif)

**Comment by Darkosto** [comment]
You mean the link above the image?

**Comment by TehNut** [comment]
I'm not able to reproduce this with just Hwyla

![](https://i.imgur.com/6bUCIUI.png)

**Comment by ChloeDawn** [comment]
Please post a mod list so this issue can be looked into properly, as it is clearly a conflicting mod.

(Apparently, this comment is aggressive lol rip so much for formality)

**Comment by Darkosto** [comment]
Give me a few minutes, I'm testing it out on stream right now. I'll let you know what I can find.

**Comment by TehNut** [comment]
Dangit @darkhax. why u do dis 2 me
