### ISSUE TITLE
Alpha Transparency Not Functioning As Intended

### ISSUE THREAD

**Issue by ChloeDawn** [TehNut-Mods/HWYLA#9]
**Setting `Alpha` to `0.0` resets tooltip to fully opaque. (Only visually, config remains at `0.0`).**

![2016-10-29_13 58 26](https://cloud.githubusercontent.com/assets/9869940/19829673/decb9d02-9ddf-11e6-96df-4f368e2627ae.png)

**Block rendering in tooltip is ignoring `Alpha` transparency values.**

![2016-10-29_13 58 33](https://cloud.githubusercontent.com/assets/9869940/19829674/dee190b2-9ddf-11e6-9d29-fa603299cd0c.png)

_Screenshots were taken with shaders active, but issue was also tested without._

**Comment by TehNut** [comment]
~~Just a note that Waila is backwards about "truly opaque" and "truly solid". `1.0` means invisible, `0.0` means solid.~~

Okay, this worked up until within the last few days. No idea what broke...
