### ISSUE TITLE
Immersive engineering IF data missing. 

### ISSUE THREAD

**Issue by ntn6371** [TehNut-Mods/HWYLA#90]
I can't see the energy (IF) details of capacitors for immersive engineering. This seems to be the same for all the wire connectors as well. I use to be able to see this in 1.10/1.11.2.

- Hwyla: Hwyla-1.8.20-B35_1.12
- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443
-Immersive Engineering: 0.12-69

**Comment by TehNut** [comment]
Tell them, then. I don't integrate with other mods. You can try enabling the energy cap provider in-game, though.
