### ISSUE TITLE
Server crashing when looking at mixer centrifugue (Embers)

### ISSUE THREAD

**Issue by JuanoD** [TehNut-Mods/HWYLA#96]
#### What happens:
https://github.com/RootsTeam/Embers/issues/257

#### Steps to reproduce:

1. Put a mixer centrifuge on a server that have the mods. Only happens in server. I tried on client and it isn't happening.
2. Look at it.

____
#### Affected Versions:

- Hwyla: 1.8.20-B35_1.12
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.0.2491

Other mods:
- Wawla-1.12.2-2.5.245
- Embers-0.221
- Bloodmoon-MC1.12-1.5.1
- TombManyGraves-1.12-4.0.2
- wolfarmor-1.12.2-2.1.0.24-RELEASE

**Comment by TehNut** [comment]
Ember issue.
