### ISSUE TITLE
NPE in console- looking at a Reliquary Pedestal?

### ISSUE THREAD

**Issue by ProsperCraft** [TehNut-Mods/HWYLA#97]
#### Issue Description:
On my multiplayer server , I see this CME/NPE in console, the other player on causes it when looking at a reliquary pedestal he said.

#### What happens:

https://gist.github.com/ProsperCraft/220d7ea50a9fa29c97938a18775ae059

#### Steps to reproduce:

1. Look at a reliquary pedestal ingame.
2. watch console
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.17-B31_1.10.2
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2316-universal

**Comment by TehNut** [comment]
They're handling null facing wrong in their getCapability.

**Comment by ProsperCraft** [comment]
Who is they? who do we forward this to so it gets fixed?

**Comment by TehNut** [comment]
...Reliquary..?

**Comment by GreatOrator** [comment]
Hopefully they are still fixing bugs in 1.10, I think they have moved on to higher versions now.
